### ISSUE TITLE
Issue with ImageMagick 6.5.4

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#101]
According to config.m4, min version is 6.2.4

RHEL-6 still have 6.5.4

During build:

      /builddir/build/BUILD/more-php56-php-pecl-imagick-3.3.0/NTS/imagick_class.c:11154: warning: implicit declaration of function 'MagickBrightnessContrastImageChannel'

At runtime

     PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/more-php56-php-pecl-imagick-3.3.0-0.4.RC2.el6.5.6.x86_64/opt/rh/rh-php56/root/usr/lib64/php/modules/imagick.so' - /builddir/build/BUILDROOT/more-php56-php-pecl-imagick-3.3.0-0.4.RC2.el6.5.6.x86_64/opt/rh/rh-php56/root/usr/lib64/php/modules/imagick.so: undefined symbol: MagickBrightnessContrastImageChannel in Unknown on line 0

Don't know is this can be fixed easily (else min version have to be updated)

**Comment by b-harper** [comment]
This issue no longer effects the base release of RHEL 6 (currently 6.7).  The version of [ImageMagick got bumped to 6.7.2.7 in RHEL 6.7][0].  This issue still effects the 6.6 EUS version of RHEL. 

Also, there is confusion regarding which versions of ImageMagick are supported.  As @remicollet  mentioned,  the config.m4 states a minium version of at least 6.2.4.  The [documentation on php.net][1] states the same.  The [pecl page][2] says 6.5.4 or higher.  The [change log][3] mentions 6.5.3-10 for 3.4.0RC1 and 3.4.0RC2.  

-Ben

[0]: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/6.7_Technical_Notes/package-ImageMagick.html
[1]: http://php.net/manual/en/imagick.requirements.php
[2]: https://pecl.php.net/package/imagick
[3]: https://pecl.php.net/package-changelog.php?package=imagick&release=3.4.0RC2

**Comment by Danack** [comment]
"The pecl page says 6.5.4 or higher. The change log mentions 6.5.3-10" 

@b-harper The version number returned by ImageMagick does not include the bugfix number. e.g. running `/usr/sbin/bin/MagickWand-config --version` returns 6.9.2 Q16. I can change the PECL page to say the exact bugfix version number.

> the config.m4 states a minimum version of at least 6.2.4. 

I have not deliberately prevented Imagick compiling against ImageMagick 6.2.4 and similar have not made any changes that would prevent it being compiled against PHP versions < 5.4.

However those versions are ancient, and anyone who is trying to use new versions of Imagick with them is doing so at their own risk. 

Up until recently those versions were included in the Travis automated tests, however I decided to remove testing against those ancient versions as the build matrix is [still too large](https://travis-ci.org/mkoppanen/imagick/builds/95251416), even with those versions removed.

I am open to suggestions of how to improve the information in this library; however the fundamental problem seems to be that ImageMagick does not follow anything close to semver, which makes encapsulating the exact version requirements be hard.

**Comment by b-harper** [comment]
Hey @Danack,

Thanks for the timely reply.  When attempting to rebuild packages for the new stable imagick 3.3.0 release, I noticed the issue @remicollet reported.  During troubleshooting, I was trying to determine the required version of ImageMagick for all functionality found in imagick 3.3.0 release.  That's when I noticed all the different versions and got confused.  

It does appear that ImageMagick does not make this easy with their crazy release numbers.  I can also understand providing flexibility with older releases.  Maybe just noting the version of ImageMagick required for all functionality in a given version of imagick?  Not sure how difficult that might be to maintain.

**Comment by carlwgeorge** [comment]
So regardless of how ImageMagick handles version numbers, the core issue seems to be that `MagickBrightnessContrastImageChannel` isn't included in the version of ImageMagick that is in RHEL 6.6.  Is there a way to make then need for that function optional via compile flags?

**Comment by Danack** [comment]
@carlwgeorge  the way we have been dealing with these in the past is to add #ifdef around the code, and to not attempt to compile the functions that aren't going to be available.

It looks like MagickBrightnessContrastImage was added in [version 6.5.9](http://upstream.rosalinux.ru/compat_reports/imagemagick/6.5.8.10_to_6.5.9.0/abi_compat_report.html#Added) but there is a lack of ifdef around it.

I'll add the ifdef, but if that one has been missed, there could be others.

Does anyone know of a command for libtool that makes it scan dynamically linked libraries to ensure that there are no missing symbols?

The alternative of compiling Imagick statically against PHP in Travis would theoretically be possible, but something I would prefer to avoid.

**Comment by Danack** [comment]
This should be fixed in release [3.4.0RC3](https://pecl.php.net/package/imagick/3.4.0RC3).

~~Mental~~ actual notes for myself:

* Just add the specific version to the travis env settings. Most of the time these issues will show up due to the cflags should report this issues.

* If that fails run the [symbol analyzer](https://github.com/mkoppanen/imagick/blob/master/util/genSymbols.sh), which will double check the symbols defined in the libraries, in a totally legitimate way and definitely not a massive hack.

**Comment by b-harper** [comment]
I just did a quick test and was able to confirm that module does build and no longer throws the runtime error.

Thanks.
