### ISSUE TITLE
Unable to catch exception when Imagicking a PDF file

### ISSUE THREAD

**Issue by kenaddams42** [mkoppanen/imagick#102]
Hi !
When I try to convert the following PDF to JPG (with PHP or command line tool), I am unable to catch any exception. The routine hangs, no error message, I have to hit CTRL-C to stop.

PDF file : 
http://tempsend.com/E99039AF8C

Error message : 
root:/tmp# convert PDF_BAD.pdf  toto.jpg
   **** Warning:  An error occurred while reading an XREF table.
   **** The file has been damaged.  This may have been caused
   **** by a problem while converting or transfering the file.
   **** Ghostscript will attempt to recover the data.
warning: ignoring zlib error: incorrect data check
   **** Warning: can't process font stream, loading font by the name.
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
warning: ignoring zlib error: incorrect data check
   **** Warning: can't process font stream, loading font by the name.
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Unknown operator: '608.77.00675' looks like a malformed number, replacing with 0.
   **** Unknown operator: '841.895.865' looks like a malformed number, replacing with 0.
   **** Unknown operator: '0.01-0.148' looks like a malformed number, replacing with 0.
   **** Unknown operator: '5.2627Q'
   **** Unknown operator: '-0.7.08m'
   **** Unknown operator: '5.44.2958' looks like a malformed number, replacing with 0.
   **** Unknown operator: '8m'
   **** Unknown operator: '1-0.101' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'v5-0.017'
   **** Unknown operator: '-0.00-0.039' looks like a malformed number, replacing with 0.
   **** Warning: Invalid operator '-' is assumed to be a number 0.
   **** Warning: Invalid operator '-' is assumed to be a number 0.
   **** Unknown operator: '-v'
   **** Unknown operator: 'l247.0067'
   **** Unknown operator: '-0.003046-0.025' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'c4c'
   **** Unknown operator: 'c002'
   **** Unknown operator: '0.018890.369' looks like a malformed number, replacing with 0.
   **** Unknown operator: '9c'
   **** Unknown operator: 'l597.00674320'
   **** Unknown operator: 'ccm'
   **** Unknown operator: '-0.08cm'
   **** Unknown operator: '6-0.005863' looks like a malformed number, replacing with 0.
   **** Unknown operator: '0.01-0.148' looks like a malformed number, replacing with 0.
   **** Unknown operator: '2-323' looks like a malformed number, replacing with 0.
   **** Unknown operator: '-32cm'
   **** Unknown operator: '0.537.6465.0067464' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'c1'
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Unknown operator: '-0.4-1.4.102' looks like a malformed number, replacing with 0.
   **** Unknown operator: '0q'
   **** Unknown operator: '2c'
   **** Unknown operator: 'l85234'
   **** Unknown operator: 'l7S'
   **** Unknown operator: '1q'
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Unknown operator: '232.w'
   **** Unknown operator: '-0.051.12' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'm1'
   **** Unknown operator: '2.065..363c'
   **** Unknown operator: '-42.065.' looks like a malformed number, replacing with 0.
   **** Unknown operator: '4.9.0' looks like a malformed number, replacing with 0.
   **** Unknown operator: '2944.524.918' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'l40'
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Unknown operator: 'l-0.723'
   **** Unknown operator: 'l-0.139'
   **** Unknown operator: 'l-0.133-0.047'
   **** Unknown operator: 'l-0.133-0.649'
   **** Unknown operator: 'l-0.139'
   **** Unknown operator: '0.515-0.197' looks like a malformed number, replacing with 0.
   **** Unknown operator: '363..262' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'l-0.173-0.047'
   **** Unknown operator: 'l-0.173-0.657'
   **** Unknown operator: '0.515-0.138' looks like a malformed number, replacing with 0.
   **** Unknown operator: '3-6.7935' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'm-1.479'
   **** Unknown operator: '0.035-0.146' looks like a malformed number, replacing with 0.
   **** Unknown operator: 'l-00723'
   **** Unknown operator: '0lm'
   **** Unknown operator: 'l-0.523'
   **** Unknown operator: 'l-00723'
   **** Unknown operator: '-0135-0.423' looks like a malformed number, replacing with 0.
   **** Unknown operator: '0lm'
   **** Unknown operator: '0lm'
   **** Unknown operator: '0lm'
   **** Unknown operator: '0.010lm'
   **** Unknown operator: '0.010lm'
   **** Unknown operator: '0.010lm'
   **** Unknown operator: '0.010lm'
   **** Unknown operator: '0lm'
   **** Unknown operator: '0lm'
   **** Unknown operator: '0lm'
^C

Thank you for your support,
Ken.

**Comment by Danack** [comment]
It looks like the file is damaged, and that is causing bad behaviour in ghostscript. Ghostscript 8 seems to be doing bad behaviour of outputting error messages to stdout. This bad behaviour doesn't occur with Ghostscript version 9.1.6

This was tested with the two commands:

    gs -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dGraphicsAlphaBits=4 -sOutputFile=output_8.png PDF_BAD.pdf > gs_stdout.txt 2> gs_stderr.txt

    ./gs-916-linux_x86_64 -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dGraphicsAlphaBits=4 -sOutputFile=output_gs916.png PDF_BAD.pdf > gs916_stdout.txt 2> gs916_stderr.txt


Ghostscript version 9.1.6 still sends error messages to stderr, but that shouldn't be a problem, as that is the correct place to send error messages. 

You should be able to download the latest version of GS from http://www.ghostscript.com/download/gsdnld.html

**Comment by Danack** [comment]
Closing, I don't believe there is an issue to address in Imagick.
