### ISSUE TITLE
ImagickException: Unable to read image from the filehandle

### ISSUE THREAD

**Issue by hanxiansen** [mkoppanen/imagick#105]
hi ! i'm in trouble 
this is my code:
```
<?php
// header("content-type: image/jpeg");
$handle = fopen('http://i3.tietuku.com/2afd667e3eded5e0.png', 'rb');
$img = new Imagick();
$img -> readImageFile($handle);

echo $img;
?>
```
I write thses code from PHP api [http://php.net/manual/en/imagick.readimagefile.php](http://php.net/manual/en/imagick.readimagefile.php)

but I still met the bug (imageException) :100: 
![](http://i3.tietuku.com/6f4d6c8f494097f0.png)
```
Fatal error: Uncaught exception 'ImagickException' with message 'Unable to read image from the filehandle' in D:\wampServer\www\test\index.php on line 7
( ! ) ImagickException: Unable to read image from the filehandle in D:\wampServer\www\test\index.php on line 7
```

How can i fix this bug?

Thanks  for  help ...

**Comment by Danack** [comment]
> How can i fix this bug?

Download the file to your machine first using something like curl.

That is far better suited to downloading files, and will give you sensible error messages.
