### ISSUE TITLE
Converting image from Grayscale to RGB

### ISSUE THREAD

**Issue by cmodijk** [mkoppanen/imagick#109]
I'm tying to convert an image from Grayscale setting to RGB but it's not working using Imagick

```
$imagick = new \Imagick($sourcePath);
$imagick->setImageType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->transformImageColorspace(\Imagick::COLORSPACE_SRGB);
$imagick->writeImage($imagePath);
```

After this command i'm using `identify` to get details about the generated image and this is the result. 
`JPEG 1280x720 1280x720+0+0 8-bit Gray 256c 44.6KB 0.000u 0:00.000`

When I try the `convert` cli with the following it works
`convert image.jpg -set colorspace RGB -type truecolor image_rgb.jpg`

I'm not sure if i'm doing anything wrong here 

Versions 
* ImageMagick 6.9.2-0 Q16 x86_64 2015-09-04 http://www.imagemagick.org
* imagick 3.3.0RC2 beta

**Comment by Danack** [comment]
Running that code and then calling `identify output.jpg` give the output:

> output.jpg JPEG 512x512 512x512+0+0 8-bit Gray 256c 65.6KB 0.000u 0:00.000

That was tested with the image from http://people.sc.fsu.edu/~jburkardt/data/jpg/lena.jpg 

Or to put it another way - I cannot reproduce the problem. Can you test with that image and do obvious double-checking of what the code is actually doing, and then if it's still an issue, post the image that you're having trouble with.

**Comment by cmodijk** [comment]
Your output is still in Gray `Gray 256c` and i want it to convert to RGB

**Comment by Danack** [comment]
Sorry, yep completely misread that.

Apparently it is an internal optimisation ImageMagick does if the image only contains gray colors to output it as grayscale. Try adding an explicit call to setType:

$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);

Which should force the output type to be what you want.

**Comment by cmodijk** [comment]
@Danack Tnx that seems to work! But I thought i tried that option but it seems to work.

**Comment by cmodijk** [comment]
I have some other problem but I don't know if it's related with the following test code it exits with an `Segmentation fault`

```
<?php

$sourcePath = 'lena.jpg';

echo exec('identify ' . $sourcePath) . "\n";

$imagick = new \Imagick($sourcePath);
$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->transformImageColorspace(\Imagick::COLORSPACE_SRGB);
$imagick->writeImage($sourcePath);

echo exec('identify ' . $sourcePath) . "\n";
```

**Comment by Danack** [comment]
The usual way to investigate segfaults it to install valgrind and run the program through that. 

valgrind /usr/local/bin/php test.php

It will (should) tell you where the segfault is occurring in a reasonably cryptic way. Can you paste the output it gives. There's a good chance it will be in the library that is being used for JPEG encoding/decoding.

**Comment by cmodijk** [comment]
Here is the valgrind output but i don't see an error in this right?

```
==9546== Memcheck, a memory error detector
==9546== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==9546== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==9546== Command: php convert.php
==9546== 
bigdata/lena.jpg JPEG 512x512 512x512+0+0 8-bit Gray 256c 65.6KB 0.000u 0:00.000
bigdata/lena.jpg JPEG 512x512 512x512+0+0 8-bit sRGB 67.8KB 0.000u 0:00.000
==9546== 
==9546== HEAP SUMMARY:
==9546==     in use at exit: 105,907 bytes in 2,784 blocks
==9546==   total heap usage: 36,533 allocs, 33,749 frees, 14,927,328 bytes allocated
==9546== 
==9546== LEAK SUMMARY:
==9546==    definitely lost: 6,392 bytes in 30 blocks
==9546==    indirectly lost: 10,525 bytes in 40 blocks
==9546==      possibly lost: 368 bytes in 1 blocks
==9546==    still reachable: 88,622 bytes in 2,713 blocks
==9546==         suppressed: 0 bytes in 0 blocks
==9546== Rerun with --leak-check=full to see details of leaked memory
==9546== 
==9546== For counts of detected and suppressed errors, rerun with: -v
==9546== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 318 from 9)
```

**Comment by Danack** [comment]
Yep, there's no segfault in there. It might be only happening randomly, try just running lots of times through valgrind to see if it happens to trigger. Alternatively you could try triggering it through GDB, which has some [instructions here](https://bugs.php.net/bugs-generating-backtrace.php).

Oh, and the other thing to look at is the notes about OpenMP:  https://github.com/mkoppanen/imagick#openmp and turn that off.

**Comment by cmodijk** [comment]
Turning off the OpenMP solves the problems tnx @Danack
