### ISSUE TITLE
Homebrew formula for PHP7-compatible branch

### ISSUE THREAD

**Issue by Alhadis** [mkoppanen/imagick#112]
Since Imagick's original source code isn't currently compatible with PHP7, it'd be ace to have a version of the module we could install for PHP7 with [Homebrew](https://github.com/Homebrew/homebrew).

I compiled it against mine, but it just got eaten up by the latest release candidate upgrade. :(

**Comment by Danack** [comment]
Why not try this branch https://github.com/mkoppanen/imagick/tree/phpseven ?

**Comment by Alhadis** [comment]
Well, that's what I did... but that branch doesn't appear to be installable by Homebrew, and the whole point of a package manager is to, well, simplify the update-and-stay-updated process.

Sooo in other words, that'll mean recompiling/reinstalling the module by hand every time the PHP interpreter gets upgraded...

**Comment by Danack** [comment]
>  that'll mean recompiling/reinstalling the module by hand every 

Couldn't you make a script to do that? Or tell Homebrew to use that branch?

Or to put it more simply, I'm not sure what you're requesting other than maybe finish off the release for 7.

**Comment by Alhadis** [comment]
I'm not sure if Homebrew allows you to compile against arbitrary branches. I've seen formulae with options to install the HEAD version of a repo, but nothing about branches.

In either case, they'll only accept formulae from official sources; that is, the maintainers of a project need to be the ones submitting a formula to their database. There're different Imagick formulae for different PHP versions - [here's the Imagick formula for PHP 5.6](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-imagick.rb). It's installed with `brew info homebrew/php/php56-imagick`.

There's no `homebrew/php/php70-imagick` yet, sadly... (Hopefully I haven't explained this backwards, my head's currently in as many different places as there are PHP versions...)

**Comment by Saeven** [comment]
+1, this would certainly open the gates for many who depend on Imagick.

**Comment by Danack** [comment]
I've done RC releases for Imagick, which apparently have allowed the homebrew people to do their thing, and the formula for PHP 7 is [apparently here](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php70-imagick.rb).

**Comment by Alhadis** [comment]
Yup, all good now!

**Comment by njbarrett** [comment]
For anyone wondering, the command you're after is `brew install php70-imagick`
