### ISSUE TITLE
Typo in "tests/skipprobefourier.inc"

### ISSUE THREAD

**Issue by Alhadis** [mkoppanen/imagick#114]
I seem to be on a roll lately with noticing/reporting useless typos... *sigh*
**Branch phpseven:** tests/skipprobefourier.inc:23 -> "unavaiable"

Should be `unavailable`, obviously.

Also, this appeared a few times when I ran `make test` to verify the compiled extension against my PHP installation. It ended with a few errors, which I've already sent to your QA team. :) (Just letting you know this in case it appears as though I'm picking through individual files looking for crap to correct... LOL).

**Comment by Danack** [comment]
Thanks for reporting the typo. As I get older, and I rely on an IDE more and more, my typing skill has noticeable decreased...

> It ended with a few errors, which I've already sent to your QA team.

Er.....you would be better off raising any issues that you see here directly as:

* there's a very high chance that any error is due to something specific to your system, and I'll need to contact you to figure out what it is.
* I actually don't know where those automated results get sent to....

**Comment by Alhadis** [comment]
CRAP, sorry. Was just following the instructions generated by `make test`... heh.

Alright, here's the feedback from another build attempt:
* [`phpize/configure` - feedback](http://pastebin.com/xqzGbrEj)
* [`make` - feedback](http://pastebin.com/LdFjCTbr)
* [`make test` - feedback](http://pastebin.com/0WkeD64c)
* [`make test` - saved results](http://pastebin.com/XBmaKYYt)

I hope that helps!

**Comment by Danack** [comment]
For the exportImagePixels one, I think I fixed an issue for it in Imagick yesterday. I'm just trying to figure out if I need to submit a [fix](https://github.com/Danack/ImageMagick/commit/c191457fb4155acd0e3ce3aff2cff836a356088f) upstream or not.

For all of the deprecated warnings, Imagick follows what ImageMagick was compiled with. If you want to make those warning notices go away, compile ImageMagick with --disable-deprecated, and then re-configure Imagick against it.

The wrong pointer type is discombobulating....I'll open a new issue for that.

**Comment by Danack** [comment]
k - I've fixed the typo.

For exportImagePixels, the code in Imagick is correct now (I believe). Depending on your platform/compile/phase of moon you may need this [upstream bug fix](https://github.com/ImageMagick/ImageMagick/pull/42).

For anything else please open a new issue to track separately.

**Comment by Alhadis** [comment]
Will do, thank you very much! :D

**Comment by Danack** [comment]
For the record, I _hadn't_ fixed the code in exportImagePixels - it still had a bug as I had misunderstood 'long' to mean 'long' rather than 4 byte int.

It's fixed now *pinkie swear*.
