### ISSUE TITLE
PHP 7 failed test

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#121]
Hi,

I run various build of "phpseven" branch against php 7.0.0RC6 (IM 6.8.8, 6.9.1, 6.9.2)

The only failed test is on i386 (evrything fine on x86_64)

    TEST 25/249 [tests/025-get-color.phpt]
    ========DIFF========
    001+ QUANTUM g is wrong for colorString 'rgb(0, 50%, 0)': actual 32768 != expected 32767
    ========DONE========
    FAIL Test getColor and getColorQuantum [tests/025-get-color.phpt]

**Comment by Danack** [comment]
Can you do me a favour and say what `var_dump(\Imagick::getQuantum());`  gives?

btw there is a reasonable chance that this is a bug in ImageMagick...

**Comment by remicollet** [comment]
> Can you do me a favour and say what var_dump(\Imagick::getQuantum()); gives?

     int(65535)

> btw there is a reasonable chance that this is a bug in ImageMagick...

I agree (tested using latest 6.9.2-5)

**Comment by Danack** [comment]
I've reported this upstream - https://github.com/ImageMagick/ImageMagick/issues/54

**Comment by Danack** [comment]
The test was fixed by 27b928a5e. Apparently the i386 version was the correct behaviour and all other versions were incorrect.

**Comment by remicollet** [comment]
Just FYI, IM 6.9.2-6 is released, with the fix applied.

Building imagick + Test suite with  a806b85 is ok.
