### ISSUE TITLE
Segmentation fault (11) crashes of Imagick::readImage() with SVG

### ISSUE THREAD

**Issue by vedmant** [mkoppanen/imagick#125]
Hi, I have problem with Imagick extension, it crashes when I run readImage() method on any SVG file. I tried different versions of imagick.so 3.1.0, 3.1.2, 3.3.0RC2, result is the same. I tried to convert svg with imagemagick directly `convert -background none -density 1200 -resize 200x200 test.svg test.png`, it works fine. I tried to reinstall all PHP packages and even tried to use php-fpm, nothing helped. Is there any way I can debug imagick.so to get more information why it crashes?

CentOS Linux release 7.1.1503 (Core)
PHP Version 5.4.45
ImageMagick 6.7.8-9 2014-06-10 Q16

Please tell me if you need any more information.

**Comment by Danack** [comment]
> Is there any way I can debug imagick.so to get more information why it crashes?

Run the script from the command line through valgrind like `valgrind php test.php`. If that fails to work, you could use [gdb instead](https://bugs.php.net/bugs-generating-backtrace.php), though I think it would be good to first:

* Test against a current version of ImageMagick.

* Provide an example SVG file that shows this behaviour.

> ImageMagick 6.7.8-9 2014-06-10 Q16

Just to note, that the date on that package is not the date it was released, but instead the date it was built (presumably). Version 6.7.8-9 was actually released on [2012-08-10](http://www.imagemagick.org/script/changelog.php)

**Comment by vedmant** [comment]
Thank you! I solved this problem with restoring droplet from image, probably it was some kind of corrupted data issue.
