### ISSUE TITLE
3.4.0_RC2 - cropThumbnailImage() not working as expected

### ISSUE THREAD

**Issue by sabl0r** [mkoppanen/imagick#132]
Hi,

having some trouble with `3.4.0_RC2` and `cropThumbnailImage()` in combination with PHP `5.6` and `7.0`. The generated image is distorted.

Everything ist working with imagick `3.1.2-r1` and `3.3.0_RC2`

Example code is provided here: https://github.com/stefket/imagick-cropThumbnailImage-test

Any ideas? Thanks!

**Comment by Danack** [comment]
Thanks for reporting this. I've found the commit [where I broke it](https://github.com/mkoppanen/imagick/commit/037d011d8fc56b47817d6275cce65daedde67014).

For the first step in fixing it, I think I'm actually going to expose the calculations that are done internally.....as currently there is no sensible way to have them be covered by a unit test, and they ought to be covered...

**Comment by sabl0r** [comment]
Thanks for the fast reply! :+1:

**Comment by Danack** [comment]
This should be fixed in release [3.4.0RC3](https://pecl.php.net/package/imagick/3.4.0RC3)

**Comment by sabl0r** [comment]
Looks good now! Thanks a lot!
