### ISSUE TITLE
Wrong phpversion("imagick")

### ISSUE THREAD

**Issue by githubjeka** [mkoppanen/imagick#133]
On branch `phpseven`

```
$ php7 -r 'var_dump(phpversion("imagick"));'
string(17) "@PACKAGE_VERSION@"
```

REL: https://github.com/avalanche123/Imagine/issues/474

**Comment by Danack** [comment]
Did you install it through Pecl or from grabbing the code? 

That version number gets built by the pecl package tool. Or at least is meant to be.

**Comment by githubjeka** [comment]
From github.

**Comment by Danack** [comment]
Then it's not an issue for Imagick as far as I am concerned. The code on github is not a PECL release, and so it would be inappropriate for it to have a PECL release number.
