### ISSUE TITLE
setImageDepth()

### ISSUE THREAD

**Issue by emxjay** [mkoppanen/imagick#134]
Is there a known issue with `setImageDepth()`?

[Details](http://stackoverflow.com/questions/34220981/setting-color-depth-with-imagick).

**Comment by Danack** [comment]
The linked question has someone linking to another answer I've already posted.

http://stackoverflow.com/a/19664192/778719

It is standard for ImageMagick to save images in the smallest size possible without loss.

If you want a specific format, please try fiddling the format options.

**Comment by emxjay** [comment]
Well, I simply want *Imagick* to keep the same depth as the input's. I though setting the depth before writing the file would overwrite the default behaviour, but it's not the case.

**Comment by Danack** [comment]
Actually _Imagick_ doesn't really control anything. It is a simple wrapper around the ImageMagick library.

For stuff like this you would usually be better off asking those guys "how to control the depth of Tiff files written, when using the MagickWand" api over at https://github.com/ImageMagick/ImageMagick .

However I had a quick look at the ImageMagick code. Apparently there is no explicit flag, but you can force it by making the image be a truetype color image.

```
$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output.tif"); 

system("identify output.tif");
```

`output.tif TIFF 200x200 200x200+0+0 16-bit sRGB 241KB 0.000u 0:00.000`

**Comment by Danack** [comment]
btw I opened a feature request at https://github.com/ImageMagick/ImageMagick/issues/66 because having to do the code above is bogus.

**Comment by emxjay** [comment]
@Danack I'm going to need your Kung Fu again, I'm afraid.

    $> identify 1.tif 2.tif 3.tif
    1.tif TIFF 2048x2048 2048x2048+0+0 16-bit Grayscale DirectClass 8.397MB 0.000u 0:00.010
    2.tif[1] TIFF 2048x2048 2048x2048+0+0 16-bit Grayscale DirectClass 8.397MB 0.000u 0:00.000
    3.tif[2] TIFF 2048x2048 2048x2048+0+0 16-bit Grayscale DirectClass 8.397MB 0.000u 0:00.000

Now, I'm assembling those guys:

    $to_append = array(1, 2, 3);
    $imagick = new Imagick();
    foreach ($to_append as $_item) {
        $imagick->addImage(new Imagick($_item . ".tif")));
    }
    $imagick->resetIterator();
    $output = $imagick->appendImages(true);
    $imagick->destroy();
    $output->setImageFormat('tiff');
    $output->setType(\Imagick::IMGTYPE_GRAYSCALE);
    $output->setImageDepth(16);
    $output->writeImages("output.tif", false);

And:

    $> identify output.tif
    output.tif TIFF 2048x6144 2048x6144+0+0 1-bit Bilevel DirectClass 1.575MB 0.000u 0:00.000

If I set the type to `IMGTYPE_TRUECOLOR`, it gives me the good color depth, but the file is way too big:

    output.tif TIFF 2048x6144 2048x6144+0+0 16-bit DirectClass 75.55MB 0.000u 0:00.000

How can I keep both the color depth and the image type of the input?

**Comment by Danack** [comment]
You could try IMGTYPE_GRAYSCALEMATTE as below, otherwise you would probably be better off asking at https://github.com/ImageMagick/ImageMagick and ask how to control the bitdepth of tiff images written through the "wand api", which is what Imagick uses.

```

$to_append = array('xc:black', 'xc:white', 'xc:black');
$imagick = new Imagick();
foreach ($to_append as $color) {
    
    $imagickAdd = new Imagick();
    $imagickAdd->newPseudoImage(20, 20, $color);
    $imagick->addImage($imagickAdd);
}
$imagick->resetIterator();
$output = $imagick->appendImages(true);
$imagick->destroy();
$output->setImageFormat('tiff');
$output->setType(\Imagick::IMGTYPE_GRAYSCALEMATTE);
$output->setImageDepth(16);
$output->writeImages("output.tif", false);

system('identify output.tif');
```

**Comment by Danack** [comment]
Also, if the command line version does what you want, then using the command line version might be the best solution.
