### ISSUE TITLE
Rename 'DrawAllocateWand' method to 'AcquireDrawingWand'

### ISSUE THREAD

**Issue by Jan-E** [mkoppanen/imagick#136]
This is a change in ImageMagick 6.9.3:
http://git.imagemagick.org/repos/ImageMagick/commit/d9d2c0db7334721f9ed0c3304226f9fa53298d18

It has to be adjusted in the PHP extension as well:
https://github.com/mkoppanen/imagick/blob/master/imagickdraw_class.c#L357

And in the phpseven branch:
https://github.com/mkoppanen/imagick/blob/phpseven/imagickdraw_class.c#L357

**Comment by Danack** [comment]
fyi the phpseven branch is redundant now. Master compiles against both PHP 5.x and 7.

Also, that poor poor semver.

**Comment by Jan-E** [comment]
@Danack  master does not compile on Windows yet, phpseven does.

**Comment by Danack** [comment]
Could you report that as a separate issue? I'm unaware of any problem: https://travis-ci.org/mkoppanen/imagick/builds/101281626

**Comment by Jan-E** [comment]
Apparently there is something wrong in my setup, as windows.php.net has them:
http://windows.php.net/downloads/pecl/releases/imagick/3.4.0rc4/

**Comment by Danack** [comment]
This should be fixed now. https://travis-ci.org/mkoppanen/imagick/builds/101712814

There's no version 6.9.3 available on launchpad so I haven't been able to add the new version to travis....I will try to remember to do that.
