### ISSUE TITLE
AutoGamma function missing from PHP API

### ISSUE THREAD

**Issue by hjnilsson** [mkoppanen/imagick#139]
While the AutoLevel function is available, the AutoGamma function that is available from the command line, as well as from the Perl and Python extensions is not bound in the PHP interface.

The source method in C can be found here: http://git.imagemagick.org/repos/ImageMagick/blob/master/MagickCore/enhance.c#L110

**Comment by Danack** [comment]
I've added it and some other missing functions into master and they will be in the next release.

The things added are:

  * Imagick::autoGammaImage([int channel = CHANNEL_ALL])
  * Imagick::autoOrient()
  * Imagick::compositeImageGravity(Imagick $image, int COMPOSITE_CONSTANT, int GRAVITY_CONSTANT)
  * Imagick::localContrastImage(float radius, float strength)
  * Imagick::DIRECTION_LEFT_TO_RIGHT
  * Imagick::DIRECTION_RIGHT_TO_LEFT
  * Imagick::SPARSECOLORMETHOD_MANHATTAN
  * ImagickDraw::getOpacity() : float
  * ImagickDraw::setOpacity(float opacity) :bool 
  * ImagickDraw::getFontResolution() : array
  * ImagickDraw::setFontResolution(float x, float y) : bool
  * ImagickDraw::getTextDirection() : bool
  * ImagickDraw::setTextDirection(int direction) : bool
  * ImagickDraw::getBorderColor() : ImagickPixel
  * ImagickDraw::setBorderColor(ImagickPixel color) : bool
  * ImagickDraw::getDensity() : string|null
  * ImagickDraw::setDensity(string density_string) : bool
  * ImagickPixel::setColorFromPixel(ImagickPixel $srcPixel) : bool

Leaving this open to remind someone to add them to the documentation.

**Comment by hjnilsson** [comment]
Excellent, thank you very much!

**Comment by Danack** [comment]
Due to finding a bug in 3.4.0, I've released 3.4.1 earlier than planned, so it should be available now.
