### ISSUE TITLE
undefined symbol: DrawSetOpacity

### ISSUE THREAD

**Issue by carlwgeorge** [mkoppanen/imagick#143]
RHEL 6.6 EUS is still using ImageMagick 6.5.4-7 (RPM version 6.5.4.7-7.el6_5).  If you build against this version, loading the imagick module raises this error.

```
undefined symbol: DrawSetOpacity in Unknown on line 0
```

At first glance this appears to be similar to #101.  I understand supporting this old version of ImageMagick isn't easy, but if you are able to apply a similar fix of adding an `#ifdef` around the affected code, it would be very appreciated.  RHEL 6.6 EUS is [supported until 2016-10-31](https://access.redhat.com/support/policy/updates/errata/#Extended_Update_Support), and the [IUS project](https://ius.io) would like our spec file to continue to work with 6.6 EUS until that time.

If this is really more trouble than it's worth, we understand, just please update the [minimum required version](https://github.com/mkoppanen/imagick/blob/c50881de00f88dd1a4405bbff6c8e20bcd979a5e/config.m4#L16) to reflect this.

**Comment by Danack** [comment]
This should be fixed in 3.4.2.

The reason this error wasn't detected was because the function wasn't working correctly even in versions where it did exist....and so the test was set to XFAIL. So although it was failing, it was failing for an unexpected reason.

Please can you try 3.4.2 and let me know if there are any others that I've gotten the version check wrong for.

**Comment by carlwgeorge** [comment]
3.4.2 compiles fine on RHEL 6.6 and the module now loads without error.  I see that version is marked as beta.  Would you consider upgrading that to stable?  We prefer to stick with stable versions for IUS packages.

**Comment by Danack** [comment]
> Would you consider upgrading that to stable?

Yeah....I just mucked up the release number (I meant to tag an RC candidate, and somehow typed beta instead) and there's no way to fix it (easily).

I'm going to tag another release in a day or two, for the changes that there were done to make compilation against ImageMagick 7 be more reliable.

Hopefully I won't make the same mistake.

**Comment by carlwgeorge** [comment]
Sounds good.  For what it's worth, it compiled and loaded fine under PHP 5.5, 5.6, and 7.0.  When the next stable release happens we'll get it packaged up.
