### ISSUE TITLE
versions IM and Imagick - question

### ISSUE THREAD

**Issue by tomkraw1** [mkoppanen/imagick#144]
If I have such errors in my PHP error log file:
`PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1681 but version 1683 is loaded. Imagick will run but may behave surprisingly `
Difference seems to be small. 

phpinfo() says that
Imagick compiled with ImageMagick version -	ImageMagick 6.9.1-2 Q16 x64
Imagick using ImageMagick library version -	ImageMagick 6.9.3-5 Q8 x64

Should I worry about version difference or shoulc I worry about quantum difference?
What version difference is rather safe?

**Comment by Danack** [comment]
I only support properly compiled versions of Imagick. If it works for you then fine, if not then weird things like http://stackoverflow.com/questions/10709488/imagemagick-missing-decode-delegates might occur.

The dates the two versions you're using are from:

2016-02-20 6.9.3-5
2015-04-19 6.9.1-2

And the changes to the API can be seen in: http://abi-laboratory.pro/tracker/timeline/imagemagick/

However the biggest difference is that one was compiled with Q16, i.e. 16bits per pixel, the other was compiled with Q8 or 8 bits per pixel. That is likely to make Imagick think some data structures are different sizes.


If you want to get rid of the error message, you can just set imagick.skip_version_check=1 in your PHP ini file....I would however just recommend downloading ImageMagick + Imagick from the same place, with them compiled against each other. e.g. from 

http://windows.php.net/downloads/pecl/deps/ and 
http://windows.php.net/downloads/pecl/releases/imagick/

**Comment by tomkraw1** [comment]
ImageMagick I downloaded from ImageMagick website and Imagick from http://pecl.php.net/package/imagick/3.4.1/windows so from the last given address.

I fixed quantum difference.

It looks all Imagick versions are Q16. Is it possible that Imagick will be compiled also with Q8?
