### ISSUE TITLE
Question - setColorspace

### ISSUE THREAD

**Issue by tomkraw1** [mkoppanen/imagick#146]
I have a photo with sRGB colorspace. When I execure \Imagick::setColorspace(imagick::COLORSPACE_RGB) to RGB then the photo is getting much brighter. What can I do to have brightness not changed?

Imagick 3.4.1 and ImageMagick 6.9.3.

**Comment by Danack** [comment]
Can you try using [Imagick::transformImageColorspace](http://php.net/manual/en/imagick.transformimagecolorspace.php) instead of set image color space. If that doesn't work, can you post an example for me to look at?

The colorspace stuff isn't always as obvious as one might hope...

**Comment by tomkraw1** [comment]
I think it works now. Is this related to changes described here http://www.imagemagick.org/script/color-management.php ? Is Imagick::transformImageColorspace aware of that changes?

**Comment by Danack** [comment]
> Is Imagick::transformImageColorspace aware of that changes?

Not really.

The difference in the functions is that `setColorspace` just changes the setting in the image that lists what colorspace the image is in.

transformColorspace changes the flag, after altering the pixels to have the same apparent brightness + colour in the new image space.

The color management changes are to do with which one is default, but Imagick isn't "aware" of them.
