### ISSUE TITLE
New function "identifyImageType()"

### ISSUE THREAD

**Issue by alex-schneider** [mkoppanen/imagick#152]
We have found out, that the "identifyImageType()" function returns better potential image types as "getImageType()".

[imagick_identify_type.patch.txt](https://github.com/mkoppanen/imagick/files/273927/imagick_identify_type.patch.txt)

**Comment by Danack** [comment]
Thanks for the patch.

This should be available now in Imagick 3.4.3RC1 -  https://pecl.php.net/package/imagick/3.4.3RC1 please let me know if it's working as you expect.

**Comment by alex-schneider** [comment]
Works great!

Thanks!
