### ISSUE TITLE
ImagickException: not authorized

### ISSUE THREAD

**Issue by lukepolo** [mkoppanen/imagick#154]
ImagickException: not authorized `/tmp/magick-1552lvf2nIjaqx1W' @ error/constitute.c/ReadImage/412 

It does not seem to be a permission issue changed my /tmp to 777

Any ideas?

**Comment by Danack** [comment]
Not really. It could by your disk is full, or otherwise gone to read only mode.

**Comment by Danack** [comment]
Closing as this will be a server configuration issue, not an Imagick issue.

**Comment by lakinmohapatra** [comment]
add it to policy.xml <policy domain="coder" rights="read | write" pattern="MSVG" />

**Comment by lakinmohapatra** [comment]
`<policy domain="coder" rights="read | write" pattern="MSVG" />`

**Comment by mathieujobin** [comment]
I solved it like this in my Dockerfile

`RUN sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml`
