### ISSUE TITLE
Tag releases in GIT

### ISSUE THREAD

**Issue by weberhofer** [mkoppanen/imagick#155]
Thank you for this great library. I'm currently packaging for opensuse and have recognized, that there are no tags on github. Would be great if you could at least tag the releases.

**Comment by Danack** [comment]
Hmm.....I'll think about it, but probably no.

The canonical releases are those listed on https://pecl.php.net/package/imagick 

The files that are in those releases are not completely identical to those on github - in particular the version information gets built as part of the pecl release process. Having tags on github of things that are almost, but not quite, the released versions doesn't sound like a good idea.

**Comment by Danack** [comment]
Hmm - I can see that having the git commit that becomes a release would be a useful thing to do....however I can't see a sane way to do this, that wouldn't cause trouble for me.

Basically to make a release, I download the source to a clean directory, and then run the command 'pear package' in the root of the Imagick folder. This goes through and does small things like putting the release version in here https://github.com/mkoppanen/imagick/blob/master/php_imagick.h#L26 and then building a tgz file which gets uploaded to pecl.php.net.

I really don't want to tag commits that don't have full information in them as the "release" - as it wouldn't be true.

Do you have any suggestions of how I could do something that satisfies your requirements, without making my own life harder?

**Comment by nubs** [comment]
What about if the tag was something like v3.4.2-src with the -src helping indicate that this isn't an actual release but just a pointer to the source tree at the time of packaging?

**Comment by weberhofer** [comment]
@Danack, how did you do it with the older, tagged versions? Are you scripted changes going back into GIT? If yes, it would be perfect; otherwise @nubs idea is good, too. Having tags simplifies to compare changes between versions sometimes.
I personally like that also to check, that projects are still alive: newer releases are a good sign!

**Comment by Danack** [comment]
> how did you do it with the older, tagged versions?

Tagged them manually by hand.....and then apparently forgot that I'd been doing that. 

> Are you scripted changes going back into GIT?

No - tbh I think the only change that is done is to put the release number here: https://github.com/mkoppanen/imagick/blob/master/php_imagick.h#L26

So the difference between the 'canonical' release, and a git version tagged right after the release is done is minimal.

So I'll go back to remembering to tag them after I do a release, and go back to add the missing tags for recent versions. Feel free to hassle me if (when) I forget to do that.

**Comment by weberhofer** [comment]
Thank you. I'll let you know if you forget :-)

**Comment by Danack** [comment]
Cool - closing then. Missing tags for the two recent releases are added.
