### ISSUE TITLE
Wheezy/Jessie with either php5-imagick ( php55/php56) or pecl 3.4.1 segfaulting

### ISSUE THREAD

**Issue by EugenMayer** [mkoppanen/imagick#156]
When running a clean wheezy (with dotdeb php55) or jessie (stable php56) and pecl imagick 3.4.1 ( or php5-imagick ) i get memory leaks and segmentation faults, see this valgrind:

as usual 

you can test this using docker and this simple images: https://github.com/EugenMayer/php-tests

```
git clone https://github.com/EugenMayer/php-tests
docker-compose build imagickjessie
docker up imagickjessie
docker exec -i -t imagickjessie bash
valgrind --leak-check=full /usr/bin/php -S localhost:8085
CMD+c
```
(same for imagickwheezy)

..this does fix this issue, but thats not a real fix for production.
```
export USE_ZEND_ALLOC=0
export ZEND_DONT_UNLOAD_MODULES=1
```

valgrind:
```
==18== HEAP SUMMARY:
==18==     in use at exit: 79,096 bytes in 2,589 blocks
==18==   total heap usage: 23,626 allocs, 21,037 frees, 4,379,576 bytes allocated
==18==
==18== 16 bytes in 1 blocks are definitely lost in loss record 4 of 85
==18==    at 0x4C28BED: malloc (vg_replace_malloc.c:263)
==18==    by 0xB03DC28: ???
==18==    by 0xB03DC65: ???
==18==    by 0xB03DA69: ???
==18==    by 0xB03F34B: ???
==18==    by 0x95663B3: ???
==18==    by 0x9566CB9: ???
==18==    by 0x9562519: ???
==18==    by 0x8EFC4EF: ???
==18==    by 0x6F1515: zend_startup_module_ex (zend_API.c:1759)
==18==    by 0x6FDA54: zend_hash_apply (zend_hash.c:716)
==18==    by 0x6F5419: zend_startup_modules (zend_API.c:1886)
==18==
==18== 104 (88 direct, 16 indirect) bytes in 1 blocks are definitely lost in loss record 28 of 85
==18==    at 0x4C28BED: malloc (vg_replace_malloc.c:263)
==18==    by 0xB03DC28: ???
==18==    by 0xB03DC65: ???
==18==    by 0xB040080: ???
==18==    by 0xB04051D: ???
==18==    by 0xB03DB67: ???
==18==    by 0x95663B3: ???
==18==    by 0x9566CB9: ???
==18==    by 0x9562519: ???
==18==    by 0x8EFC4EF: ???
==18==    by 0x6F1515: zend_startup_module_ex (zend_API.c:1759)
==18==    by 0x6FDA54: zend_hash_apply (zend_hash.c:716)
==18==
==18== 176 (16 direct, 160 indirect) bytes in 1 blocks are definitely lost in loss record 37 of 85
==18==    at 0x4C28BED: malloc (vg_replace_malloc.c:263)
==18==    by 0xB04144D: ???
==18==    by 0xB03DDD4: ???
==18==    by 0xB03F24B: ???
==18==    by 0xB03DB76: ???
==18==    by 0x95663B3: ???
==18==    by 0x9566CB9: ???
==18==    by 0x9562519: ???
==18==    by 0x8EFC4EF: ???
==18==    by 0x6F1515: zend_startup_module_ex (zend_API.c:1759)
==18==    by 0x6FDA54: zend_hash_apply (zend_hash.c:716)
==18==    by 0x6F5419: zend_startup_modules (zend_API.c:1886)
==18==
==18== LEAK SUMMARY:
==18==    definitely lost: 120 bytes in 3 blocks
==18==    indirectly lost: 176 bytes in 5 blocks
==18==      possibly lost: 0 bytes in 0 blocks
==18==    still reachable: 78,800 bytes in 2,581 blocks
==18==         suppressed: 0 bytes in 0 blocks
==18== Reachable blocks (those to which a pointer was found) are not shown.
==18== To see them, rerun with: --leak-check=full --show-reachable=yes
==18==
==18== For counts of detected and suppressed errors, rerun with: -v
==18== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 10 from 8)
```

**Comment by Danack** [comment]
Hi, please can you clarify something, I can't see any segfault in your report - where are you seeing a segfault related to Imagick?

From the other ticket "I did found a different issue mkoppanen/imagick#156 caused by imagick and xdebug" - I'm not likely to investigate any issues where xdebug is loaded. Xdebug alters how PHP behaves....in ways that aren't alway guaranteed to be safe.

**Comment by EugenMayer** [comment]
I would kindly ask you to take your time, before you judge on this. 

I even created you a dockerfile to isolate the issue. There is no xdebug - there is not even any other extension loaded  https://github.com/EugenMayer/php-tests/blob/master/imagick/wheezy/Dockerfile#L16 its a fresh jessie/wheezy installation with php + imagick only.

I just mentioned, that there is also an issue with xdebug, but this is neither related to this issue, nor to the issue with mongodb.

Valgrind indicates that the garbage collector does either not cleanup space or does cleanup space he should not have too, that means, you end up either having nullpointers or blowing up the memory - this leads to segfaults or any kind of behavior.

You might pickup GDB and the needed debugsymbols to bring it down to the level where you can graps, what is causing this issue

**Comment by Danack** [comment]
> that the garbage collector does either not cleanup space

There is no garbage collection in C. All allocations have to be freed by hand.

> Valgrind indicates ...does cleanup space he should not have too, that means, you end up either having nullpointers or blowing up the memory

The report you said does not show that. It just shows that 296 bytes of memory was still allocated when the program quit.

This does not imply anything about null pointers, and it does not imply anything about segfaulting on a bad memory access. It just means that some bytes were still allocated when the program ended.

Seeing as it's in the PHP builtin server (which is explicitly not meant to be used for production), on a operating system that makes their own changes to the PHP code, it's really hard for me to care about this. 

If you want to do the GDB tracing of exactly where the leak is coming from, then go for it.....I'm unlikely to.

**Comment by EugenMayer** [comment]
giving up on this, no time to drive this forward.

- For the GC part, it is done and is part of issues also in other extension.
- for running valigrind with "the internal server does not make sense" - then you might want to let those guys change their docs https://bugs.php.net/bugs-getting-valgrind-log.php .. and ask the php core devs ot no longer show people how to debug php c extensions using this technique

But as you simply want to close this ticket, as it is obvious, i am happy to assist you doing that.
