### ISSUE TITLE
PHP 7.1 build

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#157]
When building against 7.1.0alpha1

```
/builddir/build/BUILD/php71-php-pecl-imagick-3.4.2/NTS/imagick_helpers.c: In function 'php_imagick_progress_monitor_callable':
/builddir/build/BUILD/php71-php-pecl-imagick-3.4.2/NTS/imagick_helpers.c:96:5: error: 'zend_fcall_info {aka struct _zend_fcall_info}' has no member named 'function_table'
  fci.function_table = EG(function_table);
     ^
/builddir/build/BUILD/php71-php-pecl-imagick-3.4.2/NTS/imagick_helpers.c:111:5: error: 'zend_fcall_info {aka struct _zend_fcall_info}' has no member named 'symbol_table'
  fci.symbol_table = NULL;
     ^

```

**Comment by Danack** [comment]
> A 'has no member name' error is usually a glitch in the Matrix. It happens when they change 

I need to tag a new version with a fix.

**Comment by Danack** [comment]
3.4.3RC1 is on https://pecl.php.net/package/imagick/3.4.3RC1

It should work for PHP 7.1 - JoeWatkins is going to get in touch with the Travis people about getting PHP7.1 setup on travis.

**Comment by remicollet** [comment]
Build is indeed fix, thanks (BTW, failed tests, going to about another report about those)

**Comment by Danack** [comment]
I'm going to close this, as the other issue is probably not related to the changes made for 7.1

**Comment by zshtom** [comment]
I complie this version on php 7.1.0 ，still error

fci.function_table = EG(function_table);
fci.symbol_table = NULL;

**Comment by Danack** [comment]
@zshtom Please can you specify:

i) Exactly which version of Imagick you are trying to compile
ii) The error message you see.

Also - this appears to work on Travis:
https://travis-ci.org/mkoppanen/imagick/builds/198351246
