### ISSUE TITLE
Package stability

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#159]
From https://pecl.php.net/package/imagick

3.4.1 s stable, OK
3.4.2 is beta (perhaps forgotten)
3.4.3RC1 is stable (seems wrong)

So, using the pecl command, people stalled at 3.4.1 will be updated to 3.4.3RC3

**Comment by Danack** [comment]
> 3.4.2 is beta (perhaps forgotten)

I made a mistake, and had intended it to be an RC release - but forgot to change the name to be RC....

> 3.4.3RC1 is stable (seems wrong)
> So, using the pecl command, people stalled at 3.4.1 will be updated to 3.4.3RC3

.....and I'm just bad with computers.

**Comment by mikayla-grace** [comment]
Folks, this is not the forum for IMagick problems or comments.  Its for ImageMagick source, command-line, and supported API's.

**Comment by Danack** [comment]
This is checked in the travis CI tests: https://github.com/mkoppanen/imagick/blob/master/util/check_version.php

So even I should be able to get it right now.
