### ISSUE TITLE
\Imagick::ALPHACHANNEL_RESET is undefined

### ISSUE THREAD

**Issue by dlubitz** [mkoppanen/imagick#161]
Since 3.4.3RC1 the class constant `\Imagick::ALPHACHANNEL_RESET` is undefined.

Check: `php -r 'print (defined("\Imagick::ALPHACHANNEL_RESET") ? "yes" : "no");'`

Version 3.4.3RC1 returns `no`
Version 3.1.2 returns `yes`

**Comment by Danack** [comment]
Did you use the same version of ImageMagick for both? Can you say the version?

ALPHACHANNEL_RESET isn't going to be available when Imagick is compiled against ImageMagick >= 7.0.0

**Comment by dlubitz** [comment]
Yes, you're right, it's ImageMagick 7.0.2 with Imagick 3.4.3RC1.
But isn't this constant just renamed? So you could provide this constant (legacy) for compatibility? Or was it deprecated before?

**Comment by Danack** [comment]
> Or was it deprecated before?

It was deprecated. https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/magick/image.h#L39

I don't believe PHP has a way of marking constants as deprecated.


> But isn't this constant just renamed? So you could provide this constant (legacy) for compatibility?

I am finding it quite difficult to actually even understand what has changed between ImageMagick 6 and 7 - so am finding it hard to give advice here.

Please see #162

**Comment by dlubitz** [comment]
Thanks @Danack

**Comment by Danack** [comment]
I'll leave this open to remind myself to document this.
