### ISSUE TITLE
convert rgb-psd with alpha or transparency

### ISSUE THREAD

**Issue by sfunm** [mkoppanen/imagick#168]
Refering to ImageMagick/ImageMagick#226

I'm trying to convert given rgb-psd with alpha or transparency via Imagick 3.4.1 linked against ImageMagick 7.0.2.

Same Problem exists in Imagick, I guess I have to deliver the same options via Imagick but can't find how to this.

Any suggestions how I can reproduce the given solution with imagick?

**Comment by Danack** [comment]
Please can you provide some code that shows a reproduce case, including an example image.

**Comment by sfunm** [comment]
Found a solution for the psd with transparency, alphachannel still doesn't work, see code below

```php
$im = new Imagick('alpha.psd');
$im->setImageCompressionQuality(95);
$im->writeImage('alpha.jpg');

$im = new Imagick('trans.psd');
$im->setImageAlphaChannel(imagick::ALPHACHANNEL_REMOVE); // fixes strange rgb psd transparency result, not needed in 6.8.9-9
$im->setImageCompressionQuality(95);
$im->writeImage('trans.jpg');
```


Link (zip with code and psd-files)
https://www.dropbox.com/s/7v3v29sf3faujai/psdtest.zip?dl=0

**Comment by sfunm** [comment]
Based on https://github.com/ImageMagick/ImageMagick/issues/226#issuecomment-228426903
I modified the code:

```php
$im = new Imagick();
$im->setOption('psd:alpha-unblend', 'off');
$im->readImage('alpha.psd[0]');
$im->setImageCompressionQuality(95);
$im->writeImage('alpha.jpg');
```

Seems to be working for both, the Alpha and the Transpareny (if you use the [0]-Layer notation).
Drawback: looks like you have to know if your PSD is RGB ___before___ you load it.

So, can this be considered the new way to handle this kind of images?
If yes, this issue can be closed.

**Comment by jdabs** [comment]
@sfunm Does your code still work? Is this process in the php.net docs anywhere? It looks like an important feature. I'm glad to add it.

**Comment by sfunm** [comment]
@jdabs Sorry for answering late.
Yes, code is still working (at least for that specific version).
