### ISSUE TITLE
Unrecognized color string for colorizeImage()

### ISSUE THREAD

**Issue by theatrain** [mkoppanen/imagick#171]
$img->colorizeImage('red', 1); results in this error but if i run system() with the following command it works without issue

`system('convert ' . $input . ' \( -clone 0 -fill red -colorize 100% \) -compose multiply -composite ' . $output)`
## ImageMagick Version

Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
## OS

Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial

**Comment by Danack** [comment]
Please update your code to be:

```
$img->colorizeImage('red', 1, true);
```

The previous behaviour was incorrect, and was fixed.
