### ISSUE TITLE
Rounding Issue in resizeImage()

### ISSUE THREAD

**Issue by filex** [mkoppanen/imagick#174]
Given an input image with somewhat extreme proportions such as `1x1000px` resizing may result in one dimension being `0`, which in turn results in `NegativeOrZeroImageSize`:

``` php
<?php
$i = new Imagick;
$i->newPseudoImage(1, 1000, "canvas:red");
/* throws NegativeOrZeroImageSize */
$i->resizeImage(0, 250, 0, 1);
echo $i->getImageWidth(); // should be 1
```

ImageMagick suffers from similar problems in its command line utils. It seems that it is up to the caller to prepare the desired dimensions (e.g. #91).

I propose to change `im_round_helper()` introduced in 88e557b2 to never return `0` but `1` instead. I will provide a pull-request.

**Comment by filex** [comment]
> I will provide a pull-request.

The P/R is #175. The solution works for I/M 6 & 7 and all PHP versions. However, my knowledge of the IMagick code is very limited and you may want to propose another fix.

**Comment by Danack** [comment]
Your PR is merged, it will be in the next release.
