### ISSUE TITLE
[Question] how to resize, center image 

### ISSUE THREAD

**Issue by Izopi4a** [mkoppanen/imagick#177]
I guess i will get a lot of critics asking for help here but can someone help me with how to :
- resize image ( that can be vertical or horizontal ) to lets say 450x450
- because new size wont fit original radio center the image ( center from left to right ) 
- background to be write, or without background

Thanks.

// p.s. again sorry for asking here, it just seems like most of the examples are on imagemagick not on php imagick and it hard for me to get it.

**Comment by Danack** [comment]
Sorry I don't have time to give code support.

Also, all of the examples are documented at phpimagick.com
