### ISSUE TITLE
whats the alternative for setImageOpacity when using image magick 7 ?

### ISSUE THREAD

**Issue by Izopi4a** [mkoppanen/imagick#180]
Does anyone knows the alternative for `setImageOpacity` when using imagemagick 7 ?

i see that this method doesnt exists in api for version > 7 

https://github.com/mkoppanen/imagick/blob/bd9548c426391878905b2a6bc36accc4c79f7ef7/php_imagick_defs.h#L428

**Comment by Danack** [comment]
It's meant to be `setImageAlpha` - but it looks like I missed implementing it.

I'll need to add it and do a release.

**Comment by Izopi4a** [comment]
:D , oh ok, i was worried google didnt help me :D

You can close the issue when you want then.

Cheers !

**Comment by Danack** [comment]
oh boy, apparently these all need looking at.


DrawGetExceptionType             
MagickChannelFxImage             
MagickGetImageAlhpaColor         
MagickGetImageMask               
MagickGetImageFeatures           
MagickGetImageKurtosis           
MagickGetImageMean               
MagickGetImageRange              
MagickGetImageDistortions        
MagickInterpolativeResizeImage   
MagickOptimizeImageTransparency  
MagickOrderedDitherImage         
MagickSetImageAlphaColor         
MagickSetImageMask

**Comment by Izopi4a** [comment]
thanks 👍

**Comment by sergeyklay** [comment]
@Danack Could you please create a document that describes which other functions will not work with ImageMagick 7?

**Comment by Danack** [comment]
@sergeyklay Sorry, I just realised I never replied to you. The answer is "why don't you contribute back to the project?" https://github.com/mkoppanen/imagick/issues/162
