### ISSUE TITLE
Output file write error --- out of disk space?

### ISSUE THREAD

**Issue by autowp** [mkoppanen/imagick#181]
Windows 10 x64

PHP 7.0.12 (cli) (built: Oct 13 2016 10:47:49) ( ZTS )

phpinfo imagick
```
imagick module version => 3.4.2
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 6.9.3-7 Q16 x64 2016-03-27 http://www.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 6.9.3-7 Q16 x64 2016-03-06 http://www.imagemagick.org
ImageMagick copyright => Copyright (C) 1999-2015 ImageMagick Studio LLC
ImageMagick release date => 2016-03-06
ImageMagick number of supported formats:  => 234
```

```php
$srcFilePath = 'C:\...\pictures\1.jpg';
$destFilePath = 'C:\...\format\1.jpg';

$imagick = new Imagick();
$imagick->readImage($srcFilePath);

$fp = fopen($destFilePath, 'c+');
flock($fp, LOCK_EX | LOCK_NB);
$imagick->writeImageFile($fp); 
```

throws Exception 'ImagickException' with message 'Output file write error --- out of disk space? `C:\...\pictures\1.jpg' @ error/jpeg.c/JPEGErrorHandler/322'

Zero sized file created. Don't understand what's wrong?
Why **source** file path in error message?
Sure, disk space is available and no permissions issues.

**Comment by Danack** [comment]
```
flock($fp, LOCK_EX | LOCK_NB);
```

I can see what you're trying to do, and that's not going to work.

ImageMagick does some image processing with delegate programs. These run as separate processes than PHP, and so flocking on the file is going to block those processes from being able to write to that file.

I think what you want to do, assuming I'm guessing what you want to achieve correctly, is to create the image with a new unique file name and then use http://php.net/manual/en/function.rename.php to move it to the correct filename. rename is an atomic operation.
