### ISSUE TITLE
Unrecognized color string for colorizeImage() and tintImage()

### ISSUE THREAD

**Issue by reinvanoyen** [mkoppanen/imagick#182]
I just updated Imagick from 3.3.0 to 3.4.0.

This seems to break the old usage of the methods `colorizeImage` and `tintImage` eg:
```php
$imagick->colorizeImage('rgba(150,90,50)', 1);
```

I get an `Unrecognized color string for colorizeImage()`.

The changelog states:
> Imagick::colorizeImage() and Imagick::tintImage were using the wrong behaviour. 
> It is now fixed and the legacy behaviour can still be used by passing a 3rd parameter of `true` to the function to indicate that the legacy behaviour is desired.

What exactly does "wrong behaviour" mean? How exactly are the methods meant to be used now (without adding the 3rd parameter..)? Do they only accept a ImagickPixel object now?

**Comment by Danack** [comment]
> What exactly does "wrong behaviour" mean? 

It was not passing the value into the underlying ImageMagick library correctly. It was passing in a 'PixelWand' (which is how ImageMagick stores colors), with just the opacity set, not the RGB channels.

It wasn't possible to reproduce the results of using tint image from the ImageMagick command line tools in Imagick

If you want to see the code, it's in https://github.com/mkoppanen/imagick/blob/master/imagick_class.c

```
	if (legacy) {
		opacity_wand = php_imagick_zval_to_opacity(opacity_param, IMAGICK_CLASS, &opacity_allocated TSRMLS_CC);
		}
	else {
		opacity_wand = php_imagick_zval_to_pixelwand(opacity_param, IMAGICK_CLASS, &opacity_allocated TSRMLS_CC);
	}
```

**Comment by Danack** [comment]
And yes, please pass in `true` as the 3rd parameter to make your code work again:

```
$imagick->colorizeImage('rgba(150,90,50)', 1, true);
```

seems to work for me.

**Comment by bobmagicii** [comment]
lots of stupid things brought me here to this thread from 2016 in 2021 - your fix for my completely unrelated problem was perfect, but do you by chance know how to make this function work *without* the new argument for legacy support?

like is php just stupid, and that this function can never work ever without this argument? such that it should always just be true and not exist?

sorry just digging for knowledge here so i can blog about what made me mad today and maybe save others from it.

**Comment by Danack** [comment]
Seems to work for me. Please open an new issue if you want help.

```
$imagick = new \Imagick();
$imagick->newPseudoImage(640, 480, "magick:logo");
$opacity = $opacity / 255.0;
$opacityColor = new \ImagickPixel("rgba(255, 0, 0, 0.5)");
$imagick->colorizeImage($color, $opacityColor);

$imagick->setImageFormat('png');
$imagick->writeImage(__DIR__ . "/colourize_new.png");
```

![colourize_new](https://user-images.githubusercontent.com/1505719/122130705-f25e8e80-ce2f-11eb-95a9-0d2bf6698966.png)

```
$imagick = new \Imagick();
$imagick->newPseudoImage(640, 480, "magick:logo");
$opacity = $opacity / 255.0;
$opacityColor = new \ImagickPixel("rgba(0, 0, 0, $opacity)");
// TODO - legacy mode of setting fraction as transparency needs
// to be removed.
$imagick->colorizeImage($color, 0.5, true);
$imagick->writeImage(__DIR__ . "/colourize_old.png");
```
![colourize_old](https://user-images.githubusercontent.com/1505719/122130730-fa1e3300-ce2f-11eb-91c3-2d2423acc852.png)
