### ISSUE TITLE
@PACKAGE_VERSION@ is not defined in RC2

### ISSUE THREAD

**Issue by MaikWagner** [mkoppanen/imagick#194]
If you use `php -i` to figure out what the actual package version is you get the following output:
```text
imagick

imagick module => enabled
imagick module version => @PACKAGE_VERSION@
```
There is only the placeholder.

Its not properly defined in _php_imagick.h_.
```c++
/* Define Extension Properties */
#define PHP_IMAGICK_EXTNAME    "imagick"
#define PHP_IMAGICK_VERSION    "@PACKAGE_VERSION@"
#define PHP_IMAGICK_EXTNUM     30403
```

**Comment by Danack** [comment]
How did you install Imagick?

The version number is defined correctly in the tarball available from https://pecl.php.net/package/imagick/3.4.3RC2 which is deliberately the only distribution that has a version number.

**Comment by MaikWagner** [comment]
Okay, sorry. My fault. I used the source from git (https://github.com/mkoppanen/imagick/archive/3.4.3RC2.zip). With the official sources from the pecl site everything looks fine.

**Comment by adam1010** [comment]
The compiled dll on PECL for 7.2 Windows doesn't have the module version set. Not sure if it's a Windows problem or a 7.2 problem.

When I run **phpinfo();**  I see:

imagick module version | **@PACKAGE_VERSION@**
Imagick compiled with ImageMagick version | ImageMagick 7.0.7-11 Q16 x64 2017-11-23 

It's causing other libraries to fail when they run checks on the imagick version.

http://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/php_imagick-3.4.3-7.2-ts-vc15-x64.zip
https://mlocati.github.io/articles/php-windows-imagick.html

**Comment by fahmibrillian** [comment]
@adam1010 same with me,show in phpinfo but can't use . int's show PHP:WARNING unable to load dynamic library ...

**Comment by adam1010** [comment]
@fahmibrillian So you can't use Imagick at all?  I'm not having any trouble loading the extension (I've got working code that manipulates images and PDFs) -- the problem is actually with the dompdf library that is trying to check the imagick version and is failing. 

I used the tutorial here for loading the extension: https://mlocati.github.io/articles/php-windows-imagick.html

**Comment by fahmibrillian** [comment]
@adam1010 ya, i cant use with library pdf-to-image . maybe work without library
