### ISSUE TITLE
Bug: Strange image degradation when using imagick module

### ISSUE THREAD

**Issue by mpek** [mkoppanen/imagick#203]
I cannot use a picture and some others, because it looks awful, and nothing like it shows in preview on desktop. For further explanation, there is a thread on wordpress.org, perhaps you'd like to visit:

https://wordpress.org/support/topic/strange-image-degradation/

If you have further question, I'd be happy to help.

**Comment by Danack** [comment]
If you can provide a reproducible example, either through standalone code, or through a vagrant/docker box I can have I have a look, but I don't have time to debug what is happening otherwise.

**Comment by Danack** [comment]
No feedback
