### ISSUE TITLE
Directive track_errors is deprecated

### ISSUE THREAD

**Issue by petk** [mkoppanen/imagick#212]
When building imagick extension on PHP 7.2 there is a deprecation warning after running `make`:

```
Build complete.
Don't forget to run 'make test'.

PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
```

[>> See also](https://wiki.php.net/rfc/deprecations_php_7_2#php_errormsg)

**Comment by petk** [comment]
Sorry, my bad. It's working ok. I've used the old php.ini file with track_errors=On directive set.

Closing as resolved.

**Comment by Danack** [comment]
Actually - I'll leave it open until I've removed this file:

https://github.com/mkoppanen/imagick/blob/master/tests/082_Imagick_getImageHistogram_basic.sh

which is one of the two places where track_errors is used......but that file should never have been committed.

**Comment by Danack** [comment]
Files have been removed.

**Comment by farshadfahimi1371** [comment]
could you tell me how I could solve this problem in wamp server
I upgrade my php version and now get this error

**Comment by Danack** [comment]
@farshadfahimi1371 track_errors is nothing to do with Imagick, so no.
