### ISSUE TITLE
Call to undefined method Imagick::roundCorners()

### ISSUE THREAD

**Issue by beecubu** [mkoppanen/imagick#213]
This version has no roundCorners.

I'am using Imagick 3.4.3 with ImageMagick 7.0.6-1

**Comment by xEsk** [comment]
Same here, after update to imageMagick 7.x and imagick 3.4.3 the roundCorners is missing.

"Call to undefined method Imagick::roundCorners()"

**Comment by Danack** [comment]
Yeah - it's not present for ImageMagick 7, due to the C code depending on a library function which has been removed for ImageMagick 7.

The equivalent code should be easy to do in PHP. If any cares enough to make it, I will distribute that version instead of the C code version.

For now, I have added deprecation notice so it is less of a surprise when it goes away.

**Comment by rafi-tvtime** [comment]
Yes please share the PHP version. We use this method.

**Comment by Ericzhiluo** [comment]
please provide an alternative

**Comment by xEsk** [comment]
**Round corners code example**

```php
// example values
$width = 250;
$height = 250;
$cornerRadius = 10;

// create mask image
$mask = new Imagick();
$mask->newImage($width, $height, new ImagickPixel('transparent'), 'png');
// create the rounded rectangle
$shape = new ImagickDraw();
$shape->setFillColor(new ImagickPixel('black'));
$shape->roundRectangle(0, 0, $width, $height, $cornerRadius, $cornerRadius);
// draw the rectangle
$mask->drawImage($shape);
// apply mask
$image->compositeImage($mask, Imagick::COMPOSITE_DSTIN, 0, 0);
```

**Comment by hbnuzlx** [comment]
切后的圆形图片有个黑边，请问大佬怎么解决？

**Comment by y284663247** [comment]
@hbnuzlx the same question,

**Comment by cron13** [comment]
@hbnuzlx, @y284663247 
try before composite

$image->setImageFormat("png");
$image->setImageAlphaChannel(\Imagick::COLOR_BLACK);
$image->setImageCompression(\Imagick::COMPRESSION_ZIP);
$image->setImageCompressionQuality(0);

**Comment by stilldg** [comment]
@hbnuzlx @y284663247 
@cron13's answer wasn't working for me so here's what i have:

```
	// create mask image
	$mask = new Imagick();
	$mask->newImage($image->getImageWidth(),
					$image->getImageHeight(),
					new ImagickPixel('transparent'),
					'png');

	// create the rounded rectangle
	$shape = new ImagickDraw();
	$shape->setFillColor(new ImagickPixel('magenta'));
	$shape->roundRectangle(0, 0, $image->getImageWidth(), $image->getImageHeight(), $radius, $radius);
	// draw the rectangle
	$mask->drawImage($shape);
	// apply mask
	$image->setImageMatte(1); 

	$image->compositeImage($mask, Imagick::COMPOSITE_DSTIN, 0, 0);
```
