### ISSUE TITLE
Progressive jpegs >10MB

### ISSUE THREAD

**Issue by andrews05** [mkoppanen/imagick#216]
Imagick 3.4.3
ImageMagick 6.9.5-3 (built with mozjpeg)
PHP 7.0

Imagick seems to be crashing when I try to load a progressive jpeg with a filesize >10MB.
My test image is: https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg
This image will initially work fine, but if optimized using `jpegtran -progressive` it will no longer load. If re-compressed to a size below 10MB (still encoded as progressive) it will work again.

(imagemagick on the command line has no problems)

**Comment by Danack** [comment]
> it will no longer load.

What happens instead of it loading? Also....what do you mean by load. Please provide actual code.

Also, what platform are you running it on?

**Comment by andrews05** [comment]
I believe it crashes, I get a 500 error from the server. Load as in `new Imagick($file)`.
Ubuntu 16.04.

**Comment by Danack** [comment]
Apparently that's the error message seen when Linux kills a script due to lack of memory: https://stackoverflow.com/questions/952868/generic-killed-error-in-php-script

which sounds about right as apparently it works when you reduce the image size.

**Comment by andrews05** [comment]
Thanks, you're right! Another process was eating all memory, killing it resolved the issue.
