### ISSUE TITLE
Failed test with latest ImageMagick

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#220]
Using 6.9.9-26

```
TEST 143/267 [tests/150_Imagick_setregistry.phpt]
========DIFF========
004+ Expected exception not thrown.
004- Imagick::getRegistry exception (%s)
========DONE========
FAIL Test Imagick, setRegistry and getRegistry [tests/150_Imagick_setregistry.phpt] 
```

**Comment by remicollet** [comment]
Related to https://github.com/ImageMagick/ImageMagick/commit/97a3196e5b56116154b11cbbe3a5480288072ebb#diff-5c5afa4a1bbcdec46da7d6ed6c450015

**Comment by Danack** [comment]
Thanks. I've fixed it in a slightly different way, that hopefully allows easier 'version' checking across both ImageMagick 6 and 7 versions.

```
if (isVersionGreaterEqual('6.9.9-26', '7.0.7-15')) {
    $exceptionExpected = false;
}
```

as there are going to be other things that break/get fixed in one version of IM6 and a different version in IM7
