### ISSUE TITLE
Uncaught ImagickException's on readImageFile

### ISSUE THREAD

**Issue by copperseed** [mkoppanen/imagick#225]
Hello,

I'm having some problems with an updated ImageMagick installation where `readImageFile` produces a fatal error exception using the PHP API.

I've already had this working while running PHP 5.6 and the associated version of ImageMagick but recently updated to PHP 7.2 and updated the ImageMagick version as well.

I'm fetching an image stream from Amazon S3 with fopen and then reading the image file into ImageMagick using readImageFile:

```
$blob = fopen('s3://' . $bucket . '/' . $prePath . urldecode($name), 'r');
$img = new Imagick();
$img->readImageFile($blob);
```

With a PNG image I'm getting error `PHP Fatal error:  Uncaught ImagickException: improper image header '/var/tmp/magick-193308zvjjkKvCrJv' @ error/png.c/ReadPNGImage/4229`

With a JPG image I'm getting error `PHP Fatal error:  Uncaught ImagickException: insufficient image data in file '/var/tmp/magick-19454t7LA2q6pVdqv' @ error/jpeg.c/ReadJPEGImage/1106`

**Running**

* Mac OS X 10.12.6
* PHP Version 7.2.0RC2
* Compiled: ImageMagick 7.0.7-15 Q16 x86_64 2017-12-17
* Running: ImageMagick 7.0.7-18 Q16 x86_64 2017-12-29
* Module version: 3.4.3

**Comment by Danack** [comment]
Please could you clarify what version of ImageMagick works, and which one doesn't?

**Comment by copperseed** [comment]
Unfortunately I no longer have the old install available to test against.

**Comment by Danack** [comment]
Even if you can't test against it, can you say what version the code was working for?

**Comment by copperseed** [comment]
Sorry, that's what I meant - I don't have it available to check the version.

**Comment by maxrd2** [comment]
I have the same problem. 
It's happening with PHP 7.2.1 and PHP 5.6.32. Both are using Imagick 3.4.3 from http://pecl.php.net/package/imagick. Have tried it with master branch and it's still happening.

It was working fine with PHP 5.6.30 and some older PHP 7 (not sure which, but am sure it was working).

Here are some more details on the error/exception I've managaed to figure:
NOTE: I have replaced full path name with .....
```
$fhIn = fopen("http://storage.googleapis.com/static.toked.com/2842380/1440x900/anen1440.jpg
");
$img = new Imagick();
$img->readImageFile($fhIn); // this throws:
//  ImagickException #425: insufficient image data in file `........./tmp/magick-6776fiO8eNWVsB9f'
```

I've added catch code that inspect the temp directory:
```
try {
	$res = $img->readImageFile($fhIn);
} catch(ImagickException $e) {
	if($e->getCode() == 425) {
		$file = preg_replace('!(^.*?[\'`]|[\'`].*?$)!', '', $e->getMessage());
		exec('ls -l ' . escapeshellarg(dirname($file)) . ' | grep magick', $out);
		my_dump($file, implode("\n", $out));
	}
}
```
and this was my_dump()'s output:
```
Arg #0: ........./tmp/magick-2365G93po5iLKt4c
Arg #1: -rw------- 1 max http 468750 Jan 19 14:54 magick-2365fpSAPDZjCt40
```
Exception thrown said that the data file is 'magick-2365G93po5iLKt4c' and generated file in tmp dir was 'magick-2365fpSAPDZjCt40'. Have tried to open 'magick-2365fpSAPDZjCt40' afterwards and it contains correct data and image.

**Comment by maxrd2** [comment]
Forgot to check imagemagick library version.
Version that fails is 7.0.7.21-1.
Have tried to recompile against version 6.9.9-9, and that one works fine.
Seems something changed in imagemagick 7

**Comment by Danack** [comment]
@maxrd2 Please could you try some earlier version of ImageMagick, to try to isolate where the change occurred?

**Comment by Danack** [comment]
@copperseed 

> Compiled: ImageMagick 7.0.7-15 Q16 x86_64 2017-12-17
> Running: ImageMagick 7.0.7-18 Q16 x86_64 2017-12-29

fyi, running a different version of ImageMagick compared to the one that Imagick was compiled against is not guaranteed to work.

**Comment by maxrd2** [comment]
I've tried various tags from https://github.com/ImageMagick/ImageMagick
280ba7f73 (tag: 7.0.6-8) works
1fd8b52ac (tag: 7.0.6-9) works
27f8ba82d (tag: 7.0.7-0) works
908258552 (tag: 7.0.7-5) works
7be0c046e (tag: 7.0.7-10) works
e017264a9 (tag: 7.0.7-15) works
ddbf0ed10 (tag: 7.0.7-16) works
c9d4c4ecd (tag: 7.0.7-17) Segmentation fault on readImageFile() call
652508e71 (tag: 7.0.7-18) works
eacbdd623be13633c083fd2831eeb79e5381e089 works
db48b4e03dcdec3695c8f845c1afc6e710500722 ???
ef2dc62cc31a4ce767281d8ec481b990c02d0681 works
a09307224c224a12739587bc5bd38681b1557a35 ???
8341444730923574c149994d205459bc4250d9f5 ???
2900797b15d83cdd1e694730382e19d4eb6e9437 ???
8871ec3451d544a93ba6cf58fa6e6bf25271c4a3 **works**
977fe08bf69549506243226a2c8f2488a690b28b **broken**
93b85201f (tag: 7.0.7-19) broken
f39bfc526 (tag: 7.0.7-21) broken
imagick extension was rebuilt every time

Seems that following commit is causing that issue: https://github.com/ImageMagick/ImageMagick/commit/977fe08bf69549506243226a2c8f2488a690b28b

To be sure I've rebuilt 7.0.7-21 after doing git revert 977fe08bf69549506243226a2c8f2488a690b28b, and issue is gone.
Hope that was of some help. Will you reopen [relative issue](https://github.com/ImageMagick/ImageMagick/issues/926) upstream or can it be worked around here?

**Comment by maxrd2** [comment]
Please note the difference in temporary filenames I've written above.
Exception said that the data file is 'tmp/magick-2365**G93po5iLKt4c**'.
After script finished tmp dir contained 'magick-2365**fpSAPDZjCt40**' and it had valid image.
Code changed upstream that cause the issue is in IsBlobSeekable() function, maybe something in imagick extension is passing invalid file pointer before file is actually read?

There is [another commit upstream that changes same lines](https://github.com/ImageMagick/ImageMagick/commit/f59a9b1a4d2f0fff69328271784aeced19289389) and was related to same issue as I have https://github.com/ImageMagick/ImageMagick/issues/945

**Comment by Danack** [comment]
@maxrd2 thanks for investigating. 

It's looks pretty clearly like it's a problem internal to the ImageMagick library, rather than something I've mucked up.

Does the commit f59a9b1a4d2f0fff69328271784aeced19289389 fix it for you?

If not, I'd suggest opening an new issue, or commenting on https://github.com/ImageMagick/ImageMagick/issues/945 - as the fix will need to be done there, rather than in Imagick.

**Comment by maxrd2** [comment]
@Danack that was some dumb reasoning on me, i was convinced that commit f59a9b1a4d2f0fff69328271784aeced19289389 was included in 7.0.7-21.
Have built the master branch and the problem is gone. Would be much faster if I'd tried that first :)
As far as I'm concerned this one can be closed, not sure if @copperseed wants to confirm it too.

**Comment by copperseed** [comment]
@Danack @maxrd2 still having the issue. I've downgraded PHP to 7.1.13 and also uninstalled and reinstalled imagick with no luck. Rebuilt Imagemagick itself also (7.0.7-22) all using `brew`.

**Comment by maxrd2** [comment]
@copperseed 7.0.7-21 is broken. Either build master or 7.0.7-18. You can use whatever php-imagick version. Just make sure it's built against installed imagemagick version.

**Comment by copperseed** [comment]
@maxrd2 I've tried rebuilding with `brew` using `--HEAD` which gave me version 7.0.7-23 and also tried 7.0.7-18 as well as earlier versions down to 7.0.7-15 with no luck.

What was your process? Did you use `brew` or something else?

**Comment by maxrd2** [comment]
@copperseed did git clone from https://github.com/ImageMagick/ImageMagick and then built it with configure/make, are you sure php-imagick is not building against system's imagemagick package?

**Comment by copperseed** [comment]
@maxrd2 I've never used `make` before. Do you have to `cd` into a specific folder?

**Comment by maxrd2** [comment]
@copperseed 
Here are the commands I've used to build imagemagick - change instdir to where you want files installed to (I suggest NOT to use /usr or similar system location) - do NOT use sudo/root for anything:
```
instdir=/home/max/imagemagick
mkdir ~/tmp $instdir
cd ~/tmp
git clone git@github.com:ImageMagick/ImageMagick.git
cd ~/tmp/ImageMagick
git checkout 7.0.7-22
./configure \
    --prefix="$instdir" \
    --sysconfdir=/etc \
    --with-dejavu-font-dir=/usr/share/fonts/TTF \
    --with-gs-font-dir=/usr/share/fonts/gsfonts \
    PSDelegate=/usr/bin/gs \
    XPSDelegate=/usr/bin/gxps \
    PCLDelegate=/usr/bin/gpcl6 \
    --enable-hdri \
    --enable-opencl \
    --with-gslib \
    --with-lqr \
    --with-modules \
    --with-openexr \
    --with-openjp2 \
    --with-perl \
    --with-perl-options=INSTALLDIRS=vendor \
    --with-rsvg \
    --with-webp \
    --with-wmf \
    --with-xml \
    --without-autotrace \
    --without-djvu \
    --without-dps \
    --without-fftw \
    --without-fpx \
    --without-gcc-arch \
    --without-gvc \
    --without-jbig
make -j4
make DESTDIR="$instdir/killme" install && cp -ax "$instdir/killme/$instdir/." "$instdir/." && rm -rf "$instdir/killme"
```

Here are the commands I've used to build php-imagick - change instdir to where you want files installed to (I suggest NOT to use /usr or similar system location):
```
instdir=/home/max/imagemagick
cd ~/tmp
wget https://pecl.php.net/get/imagick-3.4.3.tgz
tar -xzf imagick-3.4.3.tgz
cd imagick-3.4.3/
phpize
./configure --prefix="$instdir" --with-imagick="$instdir"
make -j4
make INSTALL_ROOT="$instdir" install
echo -e "Add following line to your php.ini\nextension=$instdir/usr/lib/php/modules/imagick.so"
```

**Comment by copperseed** [comment]
@maxrd2 Thank you! Will give this a `bash` (excuse the pun) 😉

**Comment by Placinta** [comment]
Still seeing this issue on macOS 10.12.
ImageMagick 7.0.7-29 Q16 x86_64 2018-04-22 installed via brew HEAD
imagick 3.4.3 installed via pecl 

There is no other system imagemagick installed, and confirmed that imagick picked up the latest binary by checking the pecl install output.

**Comment by Danack** [comment]
> Is opening remote http urls actually supported by imagick?
YMMV.

I strongly recommend against it.

If it works, it saves you a tiny amount of code compared to downloading the file first and then processing it.

If it doesn't work, you get weird, hard to debug errors.

**Comment by Danack** [comment]
I think this was fixed upstream. 

If anyone is still seeing the issue please can you provide a repro case.
