### ISSUE TITLE
Missing LinearGRAYColorspace

### ISSUE THREAD

**Issue by pesc** [mkoppanen/imagick#226]
ImageMagick introduced the LinearGray colorspace (sGray) in 6.9.9-28 and 7.0.7-16(http://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=33265) and dropped it in the next version. In 6.9.9-29+ and 7.0.7-17+ they introduced the LinearGray colorspace (LinearGray). 

Bot of these are missing in imagick. But for further development just "LinearGRAYColorspace" is relevant for us because the sGray is just in one MinorVersion and got dropped afterwards.

So  the Problem is that "LinearGRAYColorspace" is missing in imagick

Duplicate Bugreport from PHP-Bug [#75802](https://bugs.php.net/bug.php?id=75802) Missing the sGray

**Comment by Danack** [comment]
This will be in the next release.
