### ISSUE TITLE
Test 236_Imagick_identify_basic fails on new PHP/Imagick versions on i586 archtecture

### ISSUE THREAD

**Issue by weberhofer** [mkoppanen/imagick#246]
---- EXPECTED OUTPUT
Image geometry 640x480
---- ACTUAL OUTPUT
free(): invalid pointer

**Comment by Danack** [comment]
Please can you generate a stack trace:

http://bugs.php.net/bugs-generating-backtrace.php for *NIX and
http://bugs.php.net/bugs-generating-backtrace-win32.php for Win32 

And then I would bet one beer on this being an issue with ImageMagick rather than Imagick.

**Comment by Danack** [comment]
Closing as I don't have enough info to investigate.
