### ISSUE TITLE
[BUG] Imagick::deleteImageProperty() completely does not work

### ISSUE THREAD

**Issue by mpyw** [mkoppanen/imagick#249]
#### Problem

```php
$img = new \Imagick();
$img->readImage('gps_image.jpg');
$img->deleteImageProperty('exif:GPSLatitude'); // true
$img->deleteImageProperty('exif:GPSLatitude'); // false
$img->deleteImageProperty('exif:GPSLatitude'); // false
$img->writeImage();
```

Once it returns true but does nothing. Note that `Imagick::setImageProperty()` correctly works.

#### Environment

```ShellSession
example@localhost: ~$ php -v
PHP 7.0.16 (cli) (built: Mar  6 2017 19:45:42) ( NTS )
example@localhost: ~$ php -i | grep imagick
/etc/php-7.0.d/40-imagick.ini,
imagick
imagick module => enabled
imagick module version => 3.4.2
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 1 => 1
```

#### Related Reports

- [PHP - 【PHP】ImagickでOrientationを削除する方法(94238)｜teratail](https://teratail.com/questions/94238)
- [php - ImagickでOrientationを削除する方法 - スタック・オーバーフロー](https://ja.stackoverflow.com/questions/38254/imagick%E3%81%A7orientation%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)

**Comment by Danack** [comment]
I'll need to check upstream, but I seem to recall the ImageMagick guys saying that ImageMagick only reads exif info, it doesn't write it.

You may need to use a tool explicitly designed to manipulate exif data rather than Imagick for this.

**Comment by mpyw** [comment]
@Danack thx

BTW, why the function exists as a ImageMagick core API?

**Comment by ofaws** [comment]
I have spent 2 hours trying to remove some image properties using deleteImageProperty. It also returned me true, but upon saving - nothing was removed. In the end - stripImage helped my situation. When I did this the settings had finally saved:
$image = new Imagick();
$image->clear();
$image->readImage($path);
$image->stripImage();
$image->deleteImageProperty("png:pHYs");
$image->writeImage();
