### ISSUE TITLE
Imagemagick 6 doesn't throw exceptions on not-found registry tag any more

### ISSUE THREAD

**Issue by iainlane** [mkoppanen/imagick#251]
We noticed that the testsuite is failing in Ubuntu once we updated to Imagemagick 6.9.10-2, and [now the testsuite fails](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-cosmic/cosmic/amd64/p/php-imagick/20180811_021708_f823c@/log.gz):

```
There was 1 failure:

1) /tmp/autopkgtest.A8x0UZ/build.5CO/src/imagick-3.4.3RC2/tests/150_Imagick_setregistry.phpt
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 Temporary-path was empty at start.
 Temporary path was set correctly.
 Temporary path was listed correctly.
-Imagick::getRegistry exception (%s)
+Expected exception not thrown.
```

I bisected to find out when this happened and it looks like it was on purpose:

```
commit 97a3196e5b56116154b11cbbe3a5480288072ebb (refs/bisect/bad)
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Sun Nov 26 10:16:44 2017 -0500

    Don't throw exception if image registry tag is not found
```

So maybe this test should be dropped?

**Comment by Danack** [comment]
Could you do be a favour and find what the next tagged release after 97a3196e5b56116154b11cbbe3a5480288072ebb is please?

> So maybe this test should be dropped?

We can restrict which versions tests are run on which would probably be the correct thing to do for now.

**Comment by iainlane** [comment]
On Tue, Aug 14, 2018 at 04:46:47AM -0700, Danack wrote:
> Could you do be a favour and find what the next tagged release after 97a3196e5b56116154b11cbbe3a5480288072ebb is please?

Sure:

laney@nightingale (master|✔)> git tag --contains 97a3196e5b56116154b11cbbe3a5480288072ebb | sort -V | head -1
6.9.9-24

> > So maybe this test should be dropped?
> 
> We can restrict which versions tests are run on which would probably be the correct thing to do for now.

Could be.

I'm not a user of imagemagick or php-imagick but this sounds like an API
break to me. If you have code which expects to catch this exception
it'll suddenly start running past where it'd have thrown before?

Cheers,

-- 
Iain Lane                                  [ iain@orangesquash.org.uk ]
Debian Developer                                   [ laney@debian.org ]
Ubuntu Developer                                   [ laney@ubuntu.com ]

**Comment by Danack** [comment]
This is fixed for the next release.
