### ISSUE TITLE
Failed to open file

### ISSUE THREAD

**Issue by Irhak** [mkoppanen/imagick#255]
Hi! I don't know if I write to right thread. 

I have installed ImagickMagick 6 on Debian Jessie (and also Wheezy) through apt-get. Using imagick function I was able to create jpg version of pdfs till last month. Today I stamble upon a problem with this. Every time I try to use it to create jpg from pdf I error "Failed to open file" pop-up, even when I'm using old pdfs that worked before. Pdfs are opening normally (outside scripts that using imagick) without any problem. With jpegs there are no problems, imagick->readImage($dest) read file without any issues. 

There was no updates made in last few weeks so no new code could affect it. Especially that last week it worked fine.

Here is a fragment of the code I use:

$image = new imagick();
$image->setResolution(300, 300);
$image->readImage($dest);
$image->setImageFormat('jpg');
$image->writeImage($preview);
$image->clear();
$image->destroy();

**Comment by Danack** [comment]
Sorry, this will have been something particular to your server. Installing everything from scratch would be the way to fix it, probably.
