### ISSUE TITLE
Monochrome option not available

### ISSUE THREAD

**Issue by adam1010** [mkoppanen/imagick#256]
The `-monochrome` option does not appear to be available from imagick. 

The manual says that monochrome performs a few tasks, so it's not as simple as just converting to grayscale and adding a threshold in the same operation.  
http://www.imagemagick.org/Usage/quantize/#monochrome

Is there a way to access this feature directly?  Perhaps a way to pass raw arguments through to ImageMagick?

**Comment by Danack** [comment]
Your link implies that the 'monochrome' operation can be achieved using something like:

```
convert xc:gray20  xc:white  +append   ctrl_colors.gif   convert logo.png -colorspace Gray \           -remap ctrl_colors.gif  -normalize  mono_remap_ctrl.gif   convert -size 15x640 gradient: -rotate 90 \           -remap ctrl_colors.gif  -normalize  mono_remap_grad_ctrl.gif | convert xc:gray20  xc:white  +append   ctrl_colors.gif   convert logo.png -colorspace Gray \           -remap ctrl_colors.gif  -normalize  mono_remap_ctrl.gif   convert -size 15x640 gradient: -rotate 90 \           -remap ctrl_colors.gif  -normalize  mono_remap_grad_ctrl.gif
-- | --
convert xc:gray20  xc:white  +append   ctrl_colors.gif   convert logo.png -colorspace Gray \           -remap ctrl_colors.gif  -normalize  mono_remap_ctrl.gif   convert -size 15x640 gradient: -rotate 90 \           -remap ctrl_colors.gif  -normalize  mono_remap_grad_ctrl.gif

```

But I'm not going to have time to investigate this. I'd recommend asking on the [ImageMagick forum](https://imagemagick.org/discourse-server/) for help breaking it down into the equivalent 'MagickWand' calls, which is what the Imagick extension can call.
