### ISSUE TITLE
php-imagick doesn't read delegates.xml

### ISSUE THREAD

**Issue by Chupaka** [mkoppanen/imagick#265]
Hello.

We're trying to implement webp format reading, and came to the point where we can read webp in command line

```
# identify -list delegate | grep webp
        png<= webp      "cwebp' -quiet %Q '%i' -o '%o"
       webp =>          "dwebp' -pam '%i' -o '%o"

# identify test.webp
Decoded /tmp/magick-250323TLAtYcR8Dej. Dimensions: 2560 x 2560 . Format: lossy. Now saving...
Saved file /tmp/magick-25032C66Jtqev8YBN
test.webp PAM 2560x2560 2560x2560+0+0 8-bit TrueColor sRGB 26.21MB 0.040u 0:00.029
```

But it doesn't work in php-fpm: the error is `ImagickException: no decode delegate for this image format 'WEBP’`.

Using strace I've found that php reads several Imagick .xml files but not delegates.xml:

```
# strace php --ri imagick 2>&1 | fgrep .xml
openat(AT_FDCWD, "/usr/share/ImageMagick-6/log.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//config-Q16/log.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ImageMagick-6/log.xml", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/share/doc/imagemagick-6-common/htmllog.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.config/ImageMagick/log.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.magick/log.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/ImageMagick-6/policy.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//config-Q16/policy.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ImageMagick-6/policy.xml", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/share/doc/imagemagick-6-common/htmlpolicy.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.config/ImageMagick/policy.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.magick/policy.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/ImageMagick-6/coder.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7//config-Q16/coder.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ImageMagick-6/coder.xml", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/share/doc/imagemagick-6-common/htmlcoder.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.config/ImageMagick/coder.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/root/.magick/coder.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
```

How to force php-imagick to use delegates.xml?

**Comment by Danack** [comment]
That's odd.

Exactly which version of ImageMagick, what OS and how are you installing ImageMagick please?

(There's probably nothing I'll be able to 'fix' in Imagick, but I might be able to help identify what is causing your issue.)

**Comment by Chupaka** [comment]
It's Ubuntu 18.04 LTS, ImageMagick 8:6.9.7.4+dfsg-16ubuntu6.4 from Ubuntu repo.

**Comment by Danack** [comment]
Hi,

It looks like ImageMagick only accesses that file when it needs the info.

The command you're running doesn't touch the list of delegates, so it doesn't get loaded. Running a command that actually processes images and so needs to know about the delegate list shows it being loaded:

e.g. `CMD strace php testing.php --ri imagick 2>&1 | fgrep .xml`

Module just loaded - https://github.com/Danack/imagemagicktest/blob/master/bugs/im265/strace_output_1.txt
vs
Module loaded, and image processing done - 
https://github.com/Danack/imagemagicktest/blob/master/bugs/im265/strace_output_2.txt

The directory https://github.com/Danack/imagemagicktest/tree/master/bugs/im265 contains a reproducible environment for this.

Please open a separate issue once if webp is still causing an issue once you've got the delegate in the delegate file.

**Comment by wadjeroudi** [comment]
for posterity: https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension-with-WebP-support
(remove imagick 6 and all previous imagick files before compile)
