### ISSUE TITLE
Unable to load PDF with readImage

### ISSUE THREAD

**Issue by macintoshplus** [mkoppanen/imagick#266]
Hi,

I have a issue with an PDF on read particular page with `readimage`.

My code:
```
$img2 = new imagick();
$img2->setResolution(150,150);
$img2->readImage('myfile.pdf[0]');
```

The result:
```
Warning: Uncaught ImagickException: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r150x150' -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-6HJdAVTGPUZaD%d' '-f/tmp/magick-6rqLxq6Vsi3AB' '-f/tmp/magick-6X4u_IYGe870z'' (-1) @ error/delegate.c/ExternalDelegateCommand/462
```
If I run this command ghostscript crash:
```
'gs' -sstdout=%stderr -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r150x150' -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-6YN5qkRHURDyL' 'myfile.pdf'
```

But if I run this command on the console, ghostscript work finelly:
```
'gs' -sstdout=%stderr -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=jpeg' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r150x150' -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-6YN5qkRHURDyL' 'myfile.pdf'
```

I have change the argument  *-sDEVICE=* from *pngalpha* to *jpeg*.

PDF Metadatas:
Version: 1.6
Producer: TCPDF 5.9.129
Page count: 2
Web optimization: true
Page size: 210 x 297 mm (A4)
Protected mode: enabled

No security except: assembly and extract page.

How-to change this value with Imagick Extension in PHP code ?

**Comment by Danack** [comment]
I have no idea, or any idea if it's even possible to do it programmatically.

I suggest you do one of the following things: 

i) Ask over at https://github.com/ImageMagick/ImageMagick how to accomplish this through the ImageMagick wand api, which is what Imagick uses to talk to ImageMagick.

ii) You can change that permanently through the delegates.xml file that is installed as part of ImageMagick.

iii) Upgrade to a new version of Ghostscript that doesn't crash. Ghostscript is a standalone program, so you can normally just download and install the latest binary of it on any computer.

**Comment by Danack** [comment]
actually, closing as this is a ghostscript problem not imagick.
