### ISSUE TITLE
is failing to detect pcre on compile, pcre is on the system and in use by php

### ISSUE THREAD

**Issue by chrcoluk** [mkoppanen/imagick#272]
This is for bugfix branch updated 6 days ago

` cc -I/usr/local/include/ImageMagick-6 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I. -I/usr/local/directadmin/custombuild/imagick-bugfix_77791 -DPHP_ATOM_INC -I/usr/local/directadmin/custombuild/imagick-bugfix_77791/include -I/usr/local/directadmin/custombuild/imagick-bugfix_77791/main -I/usr/local/directadmin/custombuild/imagick-bugfix_77791 -I/usr/local/php72/include/php -I/usr/local/php72/include/php/main -I/usr/local/php72/include/php/TSRM -I/usr/local/php72/include/php/Zend -I/usr/local/php72/include/php/ext -I/usr/local/php72/include/php/ext/date/lib -I/usr/local/include/ImageMagick-6 -DHAVE_CONFIG_H -g -O2 -c /usr/local/directadmin/custombuild/imagick-bugfix_77791/imagick.c  -fPIC -DPIC -o .libs/imagick.o
In file included from /usr/local/directadmin/custombuild/imagick-bugfix_77791/imagick.c:37:
In file included from /usr/local/php72/include/php/ext/spl/spl_iterators.h:27:
/usr/local/php72/include/php/ext/pcre/php_pcre.h:29:10: fatal error: 'pcre.h' file not found
#include "pcre.h"
         ^~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/local/directadmin/custombuild/imagick-bugfix_77791`

`# php72 -i | grep pcre
Configure Command =>  './configure'  '--prefix=/usr/local/php72' '--program-suffix=72' '--enable-fpm' '--with-config-file-scan-dir=/usr/local/php72/lib/php.conf.d' '--with-curl=/usr/local/lib' '--with-gd' '--enable-gd-native-ttf' '--with-gettext' '--with-jpeg-dir=/usr/local/lib' '--with-freetype-dir=/usr/local/lib' '--with-libxml-dir=/usr/local/lib' '--with-kerberos' '--with-openssl' '--with-mcrypt' '--with-mhash' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-pcre-regex=/usr/local' '--with-pdo-mysql=mysqlnd' '--with-pear' '--with-png-dir=/usr/local/lib' '--with-xsl' '--with-zlib' '--with-zlib-dir=/usr/local/lib' '--enable-zip' '--with-iconv=/usr/local' '--enable-bcmath' '--enable-calendar' '--enable-ftp' '--enable-sockets' '--enable-soap' '--enable-mbstring' '--enable-opcache' '--enable-intl' '--enable-exif' '--with-icu-dir=/usr/local' '--with-ldap' '--with-snmp' '--with-gmp' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-pcntl' '--with-readline' 'CPP=clang-cpp39'
pcre
pcre.backtrack_limit => 1000000 => 1000000
pcre.jit => 1 => 1
pcre.recursion_limit => 100000 => 100000`

`# find /usr/local -name pcre.h
/usr/local/include/pcre.h`

**Comment by chrcoluk** [comment]
I checked for references to pcre.h inside /usr/local/php72/include/php/ext/pcre/php_pcre.h

#if HAVE_BUNDLED_PCRE
#include "pcrelib/pcre.h"
#else
#include "pcre.h"
#endif

I am no developer but this is the possible issue in that it doesnt specify the path to pcre.h but instead expects to find it in the current directory?

**Comment by Danack** [comment]
This is very likely going to be an issue local to your computer, rather than an issue with Imagick or PHP.

Please can you list the full steps you're using. Or perhaps just compile Imagick from scratch with.

```
phpize
./configure
make clean
make install
```

> is the possible issue in that it doesnt specify the path to pcre.h but instead expects to find it in the current directory?

No. It means search the current directory first, before the system directories.

It's far more likely that you've mucked something up.....like built Imagick before with one version of PHP, then recompiled and/or reinstalled PHP but not done a clean build.


> symlinking pcre.h to /usr/local/php72/include/php/ext/pcre/

That's ... not a good thing to do. Although it puts _a_ file in place, it's very likely to result in odd behaviour, as there is no guarantee that the version of the file is going to be correct.

**Comment by Danack** [comment]
I'm going to close this as I don't believe it is a problem with Imagick.

**Comment by chrcoluk** [comment]
I know how to run compile commands and the like, its not a messed up system.

Since you dont believe it to be an issue with the module I will report it as a core php bug to the php developers since the code I pasted here was from a core php file.
