### ISSUE TITLE
Please tag 3.4.4RC1 on github

### ISSUE THREAD

**Issue by weberhofer** [mkoppanen/imagick#277]
Would be great!

**Comment by Danack** [comment]
done, though pecl is still the official distribution channel.

**Comment by weberhofer** [comment]
@Danack Not only for documentationpurposes I like tagging a lot: When you visit a github project you can immediately see the project's progress. For releases you can also copy the changelog to the tag and create a "release"...

**Comment by weberhofer** [comment]
I forgot to mention that it simplifies finding differences between versions in case of regressions.
And: Thanks for tagging!
