### ISSUE TITLE
Support heic/heif

### ISSUE THREAD

**Issue by kkmuffme** [mkoppanen/imagick#280]
Imagemagick supports heic/heif images now https://github.com/ImageMagick/ImageMagick/issues/507

Would be great if imagick could add a handling for it, so Imagick::queryFormats() also returns heic.

Unfortunately the mime type for heic files if application/octet-stream which is rather broad, but that shouldn't be too big of an issue.

**Comment by Danack** [comment]
Imagick doesn't know about image formats.

You should just recompile Imagick against a version of ImageMagick that has support for that image compiled in, and it will be there for you.
