### ISSUE TITLE
PECL 3.4.4 Windows release missing  7.1/x86

### ISSUE THREAD

**Issue by AnrDaemon** [mkoppanen/imagick#282]
See https://pecl.php.net/package/imagick/3.4.4/windows

**Comment by Danack** [comment]
@AnrDaemon Whoever controls the bot, what is this meant to be saying?

The builds appear to be there at: https://pecl.php.net/package/imagick/3.4.4/windows

**Comment by AnrDaemon** [comment]
Thanks, perhaps I was too early in the morning!

**Comment by cmb69** [comment]
The downloads must have been made available nearly at the same time this ticket has been filed. :)

**Comment by AnrDaemon** [comment]
Perhaps. The difference in timestamps between 7.1/32-bit and all other builds is several hours.
