### ISSUE TITLE
setImageBias() odd behaviour - Imagick 3.1.2 - ImageMagick 6.8.8-7 Q16

### ISSUE THREAD

**Issue by thomasgf22** [mkoppanen/imagick#31]
Testing on two different environments, setImageBias() seems not to work with ImageMagick 6.8.8-7 Q16, under Linux.
The second environment I'm working with is a Windows machine, running Imagick 3.1.2 ImageMagick 6.7.7-0 Q16, setImageBias() works properly on this one.

    <?php
    $image = new Imagick(__DIR__ . DIRECTORY_SEPARATOR . '__stack__.jpg');
    
    $image->medianFilterImage(2);
    $image->setColorspace(Imagick::COLORSPACE_GRAY);
    $image->medianFilterImage(2);
    $xKernel = array(-0.70,0,0.70,-0.70,0,0.70,-0.70,0,0.70);
    //$xKernel = array(0.70,0,-0.70,0.70,0,-0.70,0.70,0,-0.70); //this kernel returns the desired result on Linux (see below)
    $max = $image->getQuantumRange();
    $max = $max["quantumRangeLong"];
    $image->setImageBias(0.50 * $max); // -bias 50%
    $image->convolveImage($xKernel, Imagick::CHANNEL_ALL);
    header('Content-type: image/jpeg');
    echo $image;

Linux's result.
![Linux result](http://i.imgur.com/5FqR4Z9.jpg)  
Windows' result.
![Windows result](http://i.imgur.com/CGhci2q.jpg)  
  
I've also realized that not only setImageBias won't work, but flips convolveImage()'s kernel. You will notice a slightly difference between both results (besides bias not being applied to the image).  
  
This is what you get on Linux if you use the same kernel for both machines:
![Linux flipped kernel](http://i.imgur.com/LlTUbV7.jpg)  
Source image:
![Source image](http://i.imgur.com/ObO2bk6.jpg)

**Comment by Danack** [comment]
I just checked against 6.9.1-4 it still appears to be broken.

**Comment by Danack** [comment]
Ok. I'm not sure this will actually be fixed in ImageMagick 6. ImageMagick 7 allows users to directly manipulate the kernels used for this type of operation.....so maybe just upgrade to that?

**Comment by Danack** [comment]
I'm going to close this issue as ImageMagick 6 is now legacy and the bias functionality has been removed for 7.

All of the convolve and other filter functions have been subsumed by the more powerful morphology function: http://phpimagick.com/Imagick/morphology?morphologyType=1
