### ISSUE TITLE
flattenImages derprecation

### ISSUE THREAD

**Issue by GrahamCampbell** [mkoppanen/imagick#45]
Is there are replacement method to use? Also, why wasn't this mentioned in the change log?

**Comment by thomasbachem** [comment]
@Danack I stumbled over this as well. `$im->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);` is NOT equivalent to `$im->flattenImages();` in that the background color from `$im->setImageBackgroundColor(...)` isn't considered. When flattening an alpha transparent PNG image, the background will always be black. Do we need to use another layer method?

**Comment by Danack** [comment]
@GrahamCampbell Pong. 

And yeah, @thomasbachem  I'm not sure what's going on. 

The ImageMagick change log says that flattenImages should be replaceable by MergeImageLayers with the flatten method......but I agree it doesn't seem to give the same result.

Someone needs to figure out what is going on.

> 2007-10-12 6.3.6-2 Anthony <anthony@griffith...>
> Consolidated the similar methods FlattenImage() and MosaicImage() into a new layers function MergeImageLayers() method, adding 'flatten' and 'mosaic' layer methods.
Addition of another similar layers method 'merge' which 'unlocks' the normal flatten/mosaic layer merger from the origin, The resulting image will have a virtual canvas of minimal size with an offset. Also images with negative offsets will not be clipped by the 'merge' form of the command. This was created for better layering of distorted images, such as panorama overlays.

**Comment by thomasbachem** [comment]
@Danack Can you reach out to ImageMagick/Anthony and clarify this? I could try as well.

**Comment by Danack** [comment]
@thomasbachem Can you post an example - I actually misspoke, mergeImageLayers is working okay for the flatten for me (mostly), it's every other type of of merge that is being weird.

**Comment by thomasbachem** [comment]
@Danack Nevermind, I realized I need to add `setImage()` like I did with `flattenImages()` as well to avoid issues:

```php
$im->setImage($im->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN));
```

Now it works identically.

**Comment by thomasbachem** [comment]
@Danack Should we add a special remark for this to the CHANGELOG? Otherwise we can close this issue.

**Comment by Danack** [comment]
@thomasbachem I just added a special remark, so closing.

**Comment by thomasbachem** [comment]
Btw I added a comment to the PHP manual: http://php.net/manual/en/imagick.flattenimages.php#116844 as well. There's also another comment mentioning what I observed – that without reassigning $im, the background will be black. So I wasn't the only one confused ;).
