### ISSUE TITLE
shell_exec doesn't work after creating Imagick object for certain images

### ISSUE THREAD

**Issue by eugene-manuilov** [mkoppanen/imagick#53]
I have extremely weird issue, which i can't explain for now. I use Imagick library to edit uploaded images and have following peace of code:

    echo shell_exec( 'which jpegoptim' );
    $image = new Imagick( '/path/to/the/image.jpg' );
    echo shell_exec( 'which jpegoptim' );

The problem is that I receive following output:

    /usr/bin/jpegoptim
    
    Warning: shell_exec(): Unable to execute 'which jpegoptim' in ... line 129

This means that `shell_exec` works properly before I create an image object and doesn't work after it. What am I doing wrong?

**Update 1:** everything work just fine if I use GD instead of Imagick, but I want to resolve that weird issue with Imagick.

**Update 2:** further more such weird behaviour appears only for certain images, some jpeg images are processed fine, some aren't.

**Update 3:** There is no issues with file permissions, GD processes the same file just fine and shell_exec works fine after it.

**Update 4:** I use Varying-Vagrant-Vagrants (https://github.com/Varying-Vagrant-Vagrants/VVV) instance to work with. So I guess you should be able to replicate that issue there. The file with Imagick class is here:

    /srv/www/wordpress-default/wp-includes/class-wp-image-editor-imagick.php

**Comment by Danack** [comment]
Closing - I need reproduce steps to reproduce.
