### ISSUE TITLE
readImage() does not support page access in array style

### ISSUE THREAD

**Issue by jakoch** [mkoppanen/imagick#68]
Example case: extract page 1 of a pdf file and save it as jpg image.

```
$i = new Imagick();
$i->setResolution(180,180);
$i->readImage('/path/to/file.pdf[0]'); // unsupported syntax
$i->setImageFormat('jpeg');
$i->writeImage('/path/to/file.jpg');
$i->clear();
$i->destroy();
```

Results in:
```
"Fatal error: Uncaught exception 'ImagickException' with message 'Invalid filename provided' Imagick->readImage()"
```

Referencing: 
- http://stackoverflow.com/q/28286358/1163786
- http://stackoverflow.com/q/11114747/1163786

**Comment by Danack** [comment]
I just tried this code:

```
        $imagick = new \Imagick();
        $imagick->setResolution(180,180);
        $imagick->readImage(realpath("images/LayerTest.psd")."[2]"); // unsupported syntax
        $imagick->setImageFormat('png');
        header("Content-Type: image/png");
        echo $imagick->getimageblob();
```

It worked as expected. 

If you still think this is an error, could you upload an example PDF somewhere. There's a small chance that it is related to that particular file.

**Comment by jakoch** [comment]
Thank you for testing, Danack.

Could you test the following line and report back if this work, too (if so i can close the issue).
`$imagick->readImage('images/LayerTest.psd[2]');`

**Comment by Danack** [comment]
Hi @jakoch,

That doesn't work - it fails because Imagick requires that the file name is passed through `realpath` to make an absolute path. That is on my list of bugs to fix: https://bugs.php.net/bug.php?id=61583 (sorry, haven't been a maintainer for that long).

btw for realpath the 'page number' to load needs to be outside of the realpath function call, otherwise it returns false. If you update those SO questions with a better answer, I'd upvote them.

**Comment by jakoch** [comment]
Yes, you are right! That's the issue: the absolute path is required.
The bad thing is, that people constantly run into this, because the PHP manual doesn't state that an absolute path is required and the majority of examples provided there simply do not use absolute paths. See http://php.net/manual/en/imagick.readimage.php

For the fix, hmm.. just a guess.
Absolute paths tend to start with the `/` character, right?
And here the filename also ends with `]` for the page syntax `[int]`.
So you could detect both and then apply realpath on the filename part 
and concat the abspath + page again.
Then there is Windows.. argz...

**Comment by Danack** [comment]
> Then there is Windows.. argz...

I actually haven't looked into it that closely. Because the other maintainers didn't fix it when PHP 5.4 was released, I'm assuming it wasn't a trivial thing to do.

But yeah.....people keep getting caught out by it, so it's a real usability problem that ought to be fixed.

**Comment by kevindeleon** [comment]
Wait...so even if I am specifying an absolute server path such as 
`$imagick->readImage('/var/www/images/LayerTest.psd[2]');`

I still have to wrap that in `realpath()` for the page specifier to work?

Because I have this code, and it does not work.

```php
$imagick = new Imagick();
$imagick->setResolution(180,180);
$imagick->readImage('/var/www/images/test.pdf[0]'); 
$imagick->setImageFormat('png');
```

It fails with the following error every time:
"Fatal error: Uncaught exception 'ImagickException' with message 'Invalid filename provided' Imagick->readImage()"

**Comment by Danack** [comment]
> so even if I am specifying an absolute server path such as 

@kevindeleon No, that should work. Specifying the full file path is the same as calling it with realpath......realpath  expands it to the full filename, assuming that it exists..

I cannot reproduce your error. 

Please can you double check that the values are actually what you think they are. The only way to get that error is by passing in either a filename longer than the max allowed (4096 bytes I believe) or to pass in a value that is a zero length string.....which is what is returned by realpath if the file doesn't exist.

https://github.com/mkoppanen/imagick/blob/master/imagick_file.c#L96-L103

**Comment by kevindeleon** [comment]
Well...to be clear, I am actually passing in a variable...not a string.  But I have verified multiple times that the string is '/var/www/application/images/test.pdf[0]'

Is passing in vars to readImage not allowed?

**Comment by kevindeleon** [comment]
A var_dump of the var being passed into readimage (right before it happens) is

`string(57) "/var/www/directory/directory/directory/directory/test123.pdf[0]"`

I am using the word directory to obscure directory names for privacy concerns.  That path does not work when passed into readImage().

I am on Ubuntu 14.04, HHVM 3.5.0

It works fine if I use just the path with no page specifier...but when the page specifier is in the string...it bombs with the error above.

**Comment by Danack** [comment]
> I am on Ubuntu 14.04, HHVM 3.5.0

You are in the wrong Github repo. Try the one for the code you are actually using:

https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext/imagick

**Comment by kevindeleon** [comment]
Sorry...followed a link to this issue from stack exchange.
