### ISSUE TITLE
Check AcquireKernelInfo("1") usage

### ISSUE THREAD

**Issue by Danack** [mkoppanen/imagick#76]
They should probably be replaced with AcquireKernelInfo(NULL)

**Comment by Danack** [comment]
This is done. Generic malloc was replaced with Aligned ImageMagick version.

**Comment by mkoppanen** [comment]
Two minor things I noticed:

This can be static:
https://github.com/mkoppanen/imagick/blob/master/imagick_class.c#L11166

There is a potential leak of "colors" variable:
https://github.com/mkoppanen/imagick/blob/master/imagick_class.c#L11220

**Comment by Danack** [comment]
Thanks - those are fixed now. I also renamed the function to make it clear that is module specific function.
