### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by RobsenInTheHouse** [mkoppanen/imagick#77]
Setting a font family always fails this check:

https://github.com/mkoppanen/imagick/blob/194ef721d8c388327cfd8ec22635d942598dfbdc/imagickdraw_class.c#L584

This happens with all font families although they are contained in convert -list font

**Comment by Danack** [comment]
This works fine for me.

Please can you check that the file that is given by `convert -list font` as containing the font list (which is `Path: /etc/ImageMagick-6/type-ghostscript.xml` for me) is accessible by the PHP process running Imagick?

If it is, then it is possible that the list of fonts isn't available for some other reason. You will need to use strace or some equivalent to investigate why that file isn't available to ImageMagick called via PHP.

e.g.  `strace /usr/local/bin/php testScript.php` will show you all of the attempts to open the file that lists the fonts.

**Comment by RobsenInTheHouse** [comment]
I think that clarifies the issue. The fonts are configured by fontconfig. The convert-list does not show a path but "Path: System Fonts".

I found a post on the imagemagick page that states the xml file is not necessary:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=15355

Some experiments:

If i call setFont() the font is selected but i have to specify the long name like "Bitstream-Vera-Sans-Mono-Roman". That is very friendly for my users.

E.g. this fails at setFontFamily, setFont works:
$draw = new ImagickDraw();
$draw->setFont("Bitstream-Vera-Sans-Mono-Roman");
$draw->setFontFamily("Bitstream Vera Sans Mono");

convert -list font looks like this:
---------------------------------
Path: System Fonts
  Font: Bitstream-Vera-Sans-Mono-Roman
    family: Bitstream Vera Sans Mono
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/VeraMono.ttf
  Font: Century-Schoolbook-Bold
    family: Century Schoolbook
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/gsfonts/c059016l.pfb

**Comment by Danack** [comment]
I just checked the behaviour with the font availability check removed, and with a font family that isn't  unavailable.

It looks like rather than return an error, ImageMagick (or the delegate it is calling) just outputs an error message to stderr.

```
php: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153.
```

I'll try compiling ImageMagick with fontconfig, to see what the behaviour is like then.

**Comment by Danack** [comment]
Hmm, @RobsenInTheHouse what distro are you running and what is the exact version of ImageMagick you're using?

I'm unable to investigate further at the moment as ImageMagick doesn't seem to want to play nicely with fontconfig on my system.

**Comment by RobsenInTheHouse** [comment]
Thank you for investigating on this issue! Here is the information:

It's my default dev env setup for web on Ubuntu 12.04 LTS Desktop and additionally the packages below. Nothing special. Everything is installed and configured rather default.

apt-get install apache2 php5 mysql-server php5-mysql phpmyadmin libfreetype6-dev libfontconfig-dev php-pear libapache2-mod-xsendfile supervisor imagemagick php5-imagick

---------------------------------------
convert -version
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC

---------------------------------------
fc-list -V
fontconfig version 2.8.0

**Comment by Danack** [comment]
So, the actual issue is simple. The `php_imagick_check_font` check is checking the font name against the family name but they are different.

```
Font: Bitstream-Vera-Sans-Mono-Roman
family: Bitstream Vera Sans Mono
```

i.e. hyphens instead of spaces. The code is almost certainly going to fail for all fonts that have family names that contain spaces.

I think the only sensible thing to do is:

1. Remove the font available check for the font-family.

2. Ask the ImageMagick guys to add a MagickQueryFontFamilies function.

**Comment by Danack** [comment]
I removed the check as it's blocking valid calls from succeeding. Without a way to validate what font-families are available, this is something that users are just going to have to be careful with.
