### ISSUE TITLE
Let's release 3.3.0!

### ISSUE THREAD

**Issue by thomasbachem** [mkoppanen/imagick#80]
Thanks to @Danack's fantastic work, I'm now looking forward to be able to use the morphology methods in production. My ops guys however are not very happy with installing an unreleased PECL extension.

I see a lot of activity in the master branch, so since the last release is nearly 1.5 years old, my question is whether you guys have any plans to release the current master soon?

**Comment by Danack** [comment]
![doilooklikeaguywithaplan](https://cloud.githubusercontent.com/assets/1505719/6428105/8be857d4-bf8c-11e4-92a2-c076ef66cd38.jpg)

Seriously though, it's planned we just need to get to it.

If you wanted to help out, going through all of the commit messages and parsing them into something somewhat sensible and then putting them in the [ChangeLog](https://github.com/mkoppanen/imagick/blob/master/ChangeLog) file would be awesome.

**Comment by thomasbachem** [comment]
I tried my best to update the changelog: #81

**Comment by Danack** [comment]
So the checklist for doing a release is:

i) ---Release notes done.--- Thanks Thomas.

ii) Figure out what needs tidying. The only thing I'm planning to do is investigate #77 I'm not guaranteeing to fix it, but I should at least understand it.

iii) Actually do the release which involves fiddling with PECL. I should have the karma to do this, but I'll only start it when we're good to go.

Is there anything else that anyone is aware of needing to be done for a release?

**Comment by thomasbachem** [comment]
Does fiddling with PECL also update the PHP docs at http://php.net/manual/en/book.imagick.php or would that be step v)?

**Comment by Danack** [comment]
It....does not affect the documentation. Although there is a script somewhere to make stub entries for all of the functions in an extension, that still leaves the actual work of writing the useful bits of the documentation.

I have karma to commit to the docs svn (yes, svn) - what I'm planning to do is make a separate converter that can take the examples + words written at phpimagick.com and generate/insert the appropriate XML (yes, XML) because otherwise it's a complete PITA to edit the docs, which is why they are so lacking, not just for Imagick, but for other things like the PHP reflection functionality.

But I'll address the docs after the release.

**Comment by thomasbachem** [comment]
Wow I just realized how great the documentation at http://phpimagick.com actually is o_O!

**Comment by Danack** [comment]
So it turns out that I do not have karma for doing the release on Pecl. I've applied for the permissions but will need them before being able to tag a version as the release.

**Comment by thomasbachem** [comment]
Regarding the stub class – is it really that much work to add the few new methods & constants?

**Comment by Danack** [comment]
It's more the fact that it needs to be generated according to the same format that the PHPStorm guys at Jetbrains use. i.e. it's not just putting the functions in but things like the version number, link to the php manual (which probably ought to exist), marking up the return values for them to be rendered correctly in DocBook format.

e.g. this is an entry taken from the current stub class that ships with PHPStorm.

	/**
	 * (PECL imagick 2.0.0)<br/>
	 * Applies a solarizing effect to the image
	 * @link http://php.net/manual/en/imagick.solarizeimage.php
	 * @param int $threshold
	 * @return bool <b>TRUE</b> on success.
	 */
	public function solarizeimage ($threshold) {}

There is a way of generating most of it from the source code...but it just really isn't that important, so lets just get the release out the door.

**Comment by Danack** [comment]
Ahhh yiss: http://pecl.php.net/package/imagick/3.3.0RC1

**Comment by thomasbachem** [comment]
:)

**Comment by mkoppanen** [comment]
Excellent work, @Danack ! :+1:

**Comment by stof** [comment]
any plan for the stable release ?

**Comment by Danack** [comment]
3.3.0 stable is released.

3.4.0 RCs are out, and that's the one that includes support for PHP 7.
