### ISSUE TITLE
Does mergeImageLayers return bool or an Imagick object?

### ISSUE THREAD

**Issue by zerocrates** [mkoppanen/imagick#86]
The php.net documentation says it returns bool: http://php.net/manual/en/imagick.mergeimagelayers.php

But, in the changelog in the tree here, the example implies that it returns an Imagick object that you have to use to get the actually-merged image:

```
$im = $im->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN)
```

Which is the correct source? From testing things out, it looks like it's the latter, you get back a different Imagick object, but I'm not totally sure.

**Comment by Danack** [comment]
It returns a new Imagick instance - https://github.com/mkoppanen/imagick/blob/master/imagick_class.c#L1822 Even if that code is hard to understand, it's quite different from the `RETURN_TRUE;` or false for other functions.

If you can update the docs that would be awesome. There's an edit button on each page to allow edits.

**Comment by zerocrates** [comment]
Thanks for the clarification.

I'd be happy to edit the documentation, but there appears to be a pending edit for that file already: the editor lists the file in red, says "File modified by anonymous #53942," and has the save icon disabled. That pending edit seems to have fixed the signature type from bool to Imagick, but left the standard inaccurate "returns TRUE on success" there.
