### ISSUE TITLE
ENFORCE_SAFE_MODE is dropped in PHP7

### ISSUE THREAD

**Issue by Jan-E** [mkoppanen/imagick#88]
@Danack 
imagick does not compile anymore because ENFORCE_SAFE_MODE is dropped in PHP7:
https://github.com/php/php-src/commit/a141ccb4ff7fb0666c7d7986c39feda9421291fe#commitcomment-10541152

ENFORCE_SAFE_MODE is used here:
https://github.com/mkoppanen/imagick/blob/phpseven/imagick_file.c#L193

I suppose you'll have to change ENFORCE_SAFE_MODE into just 0 or remove the 'ENFORCE_SAFE_MODE|'

**Comment by Danack** [comment]
Thanks. For the record, this is why the 7 stuff is in a separate branch, and not listed as supported in the pecl package.

**Comment by Danack** [comment]
The CI is still running, but this should be fixed now.

**Comment by Jan-E** [comment]
In my local copy (for Windows builds) I even shortened the line to

    stream = php_stream_open_wrapper(file->filename, "rb", IGNORE_PATH & ~REPORT_ERRORS, NULL);

The parentheses around IGNORE_PATH aren't needed anymore.
