### ISSUE TITLE
specify filter for thumbnailImage()

### ISSUE THREAD

**Issue by nwtn** [mkoppanen/imagick#90]
Would it be possible to add support to set a filter for use with `thumbnailImage()`, similar to how a filter can be set with `resizeImage()`?

So basically I'd like to be able to do the equivalent of:

````
convert -filter Triangle -thumbnail 300 input.png output.png
````

(Sorry if I'm just not spotting how this can be done currently!)

**Comment by Danack** [comment]
Sorry, nope, not possible. The underlying ImageMagick function doesn't allow filter passing.

You can get the same effect by calling [resizeImage](http://phpimagick.com/Imagick/resizeImage?imagePath=Lorikeet&filterType=28&width=200&height=200&blur=1&bestFit=1&cropZoom=0) and then calling stripImage, probably.

**Comment by nwtn** [comment]
In that case, would it be possible to set the `filter` property of the image via Imagick, so that when the underlying ImageMagick `thumbnailImage()` function is run it can pass that to `resizeImage()`?

In the underlying ImageMagick function, `image->filter` gets passed to `resizeImage()`:

````
        thumbnail_image=ResizeImage(sample_image,columns,rows,image->filter,
          exception);
````

**Comment by Danack** [comment]
Apparently not - weirdly the images filter doesn't appear to be settable through the ImageMagick API.

You could ask on the [ImageMagick forum](http://www.imagemagick.org/discourse-server/viewforum.php?f=1) whether that could be added, but I believe their philosophy is that the API isn't really intended to match the command line tool in every case, so some stuff has to be done by writing code.

```PHP
class CustomImagick extends Imagick {

    private $filter;

    function setFilter($filter) {
        $this->filter = $filter;
    }

    function thumbnailImage($width, $height) {
        //Some other code to handle the background filling.
        $this->resizeImage($width, $height, $this->filter, 1, $bestFit);
    }
}

```

**Comment by nwtn** [comment]
OK, thanks for your help with this. I'll post something over on the IM forum, but deal with it in code for the time being.
