### ISSUE TITLE
Rounding error when calculating geometry

### ISSUE THREAD

**Issue by nwtn** [mkoppanen/imagick#91]
When resizing with thumbnailImage(), if a `0` width or height is passed, Imagick calculates the appropriate size to maintain aspect ratio. The way it works currently is resulting in slightly different output dimensions than the equivalent command line operation. This is due to a difference in how fractional lengths are rounded.

E.g. Given this image:

![1a-1](https://cloud.githubusercontent.com/assets/786799/7024732/dec3306c-dd0c-11e4-88c5-5f8e2816afec.jpg)

…if I resize to 300px wide (using `$image->thumbnailImage(300, 0);`) with Imagick, the output is 262px high. If I do the same on the CLI (using `convert -thumbnail 300 input.jpg output.jpg`), the output is 263px high.

In [php_imagick_thumbnail_dimensions](https://github.com/mkoppanen/imagick/blob/dd6e80c70a842ad58705f7bd5db9b3a9fe0c5e17/imagick_helpers.c#L120), the `new_width` and `new_height` are doubles, and these get passed into the appropriate ImageMagick function. I believe that function simply truncates the doubles, rather than rounding them. In this case:

````
h = (300 / 2961) * 2592
   = 262.613975
````

By rounding the doubles to ints in `php_imagick_thumbnail_dimensions`, you should be able to get the same output as the command-line function.

**Comment by Danack** [comment]
This would probably be need to be fixed at a major version, if we decided to change it to match the behaviour in a different program.

Rounding in C89 is slightly tricky - http://blog.frama-c.com/index.php?post/2013/05/02/nearbyintf1

**Comment by Danack** [comment]
It looks like PHP 7 will target C99 which will both make this a trivial fix to implement, as well as be a good time to change the behaviour i.e. when people are upgrading a major version of PHP, so the plan is to change the behaviour then with a major release of Imagick..

**Comment by Danack** [comment]
Slight change of plan. The next release is going to be a point release targeted solely at supporting both PHP7 and also ImageMagick 7.

To avoid BC breaks we'll have to push changing the rounding stuff back to the next major release,

**Comment by Danack** [comment]
Semver is probably over-rated.

This should be fixed in release [3.4.0RC3](https://pecl.php.net/package/imagick/3.4.0RC3).

I have added a legacy flag to the functions that are affected. Setting that to true that should result in the same 'incorrect' values as before.

This flag will be removed at some point in the future.

**Comment by nwtn** [comment]
![good job](http://nwtn.ca/g/gj.gif)

**Comment by Danack** [comment]
And all the other people who were somehow [dependent on the old behaviour.](http://imgur.com/gallery/SWn14Sa)
