### ISSUE TITLE
Imagick 3.3.0rc1 MagickGetImageAttribute entry point not found

### ISSUE THREAD

**Issue by thejahweh** [mkoppanen/imagick#92]
Hi im running
* PHP 5.6.7 x86 NTS MSVC11
* ImageMagick 6.9.1-2 Q16 x86
* php_imagick 3.3.0rc1 5.6 nts vc11 x86

If I now run php in the console it gives me this error
```
php.exe - Entry Point Not Found

The procedure entry point MagickGetImageAttribute could not be located in the dynamic link library c:\apps\php56\ext\php_imagick.dll. 
```

**Comment by Danack** [comment]
Did you compile these yourself or did you download the executables from somewhere?

Both this and #93 are very likely to be compilation issues rather than issues that I will be able to fix.

**Comment by thejahweh** [comment]
I have downloaded them from http://pecl.php.net/package/imagick

This Issue is not like #93, because with version 3.3.0rc1 it could not load the PHP Module `php_imagick` at the start of PHP and it is not mentioned in `phpinfo()`.

In issue #93 PHP does start and the imagick version is mentioned in `phpinfo()`, but CLI crashes if the method `readImageFile` is used.

**Comment by Danack** [comment]
Where did you download ImageMagick 6.9.1-2 Q16 x86 from?

The version of Imagick listed on http://pecl.php.net/package/imagick was compiled against the version available here http://windows.php.net/downloads/pecl/deps/ aka ImageMagick-6.8.9-1.

> This Issue is not like #93, 

Both issues are to do with you seeing weird stuff that no-one else is seeing....

**Comment by thejahweh** [comment]
The ImageMagick versions are coming from http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/binaries/

Tested ImageMagick-6.8.9-1-Q16-x86-dll with 3.3.0rc1
```
Warning: PHP Startup: Unable to load dynamic library 'ext\php_imagick.dll' - The specified procedure could not be found. in Unknown on line 0

php.exe - Entry Point Not Found
The procedure entry point MagickGetImageAttribute could not be located in the dynamic link library c:\apps\php56\ext\php_imagick.dll. 
```
and with 3.1.2
```
Warning: PHP Startup: Unable to load dynamic library 'ext\php_imagick.dll' - The specified procedure could not be found. in Unknown on line 0

php.exe - Entry Point Not Found
The procedure entry point DrawSetStrokeAlpha could not be located in the dynamic link library c:\apps\php56\ext\php_imagick.dll. 
```

If I put the `CORE_RL_xxx_.dll` files from php_imagick in the php root folder, then I get this message with version 3.3.0rc1.
```
Fatal error: Uncaught exception 'ImagickException' with message 'NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/501' in xxx\imagick.test.php:9
Stack trace:
#0 xxx\imagick.test.php(9): Imagick->readimagefile(Resource id #5)
#1 {main}
  thrown in xxx\imagick.test.php on line 9
```

**Comment by Danack** [comment]
Please can you try using the version of ImageMagick from http://windows.php.net/downloads/pecl/deps/

That should be the version that Imagick was compiled against.

**Comment by thejahweh** [comment]
It works :smile: :tada: 

What I've done:
* Put `php_imagick.dll` 3.3.0rc1 into the PHP `ext` dir.
* Just don't install ImageMagick via the installer `dll.exe`.
* Download the `ImageMagick-6.8.9-1-vc11-x86.zip` from http://windows.php.net/downloads/pecl/deps/
* Copy the content of the `bin` dir into `C:\Program Files (x86)\ImageMagick`.
* Add `C:\Program Files (x86)\ImageMagick` to the path variable.
* ???
* Profit :moneybag:

**Comment by Danack** [comment]
This was a version mismatch problem.

**Comment by TonyBogdanov** [comment]
Thanks @thejahweh it finally worked!
