### ISSUE TITLE
Imagick 3.1.2 crashes on readImageFile

### ISSUE THREAD

**Issue by thejahweh** [mkoppanen/imagick#93]
Hi im running
* PHP 5.6.7 x86 NTS MSVC11
* ImageMagick 6.8.7-4 Q16 x86
* php_imagick 3.1.2 5.6 nts vc11 x86

If I now run my `imagick.test.php` in the console PHP just crashes on `readImageFile`
```
CLI has stopped working
```

My `imagick.test.php`
```php
$handle = fopen('test.jpg', 'rb');
$imagick = new Imagick();
$imagick->readImageFile($handle);
```

**Comment by Danack** [comment]
This was a version mismatch problem.
