### ISSUE TITLE
024-ispixelsimilar.phpt fails with recent ImageMagick

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#97]
With 6.8.8-10, test suite is OK.

With 6.9.1-4 this test fails.

     TEST 23/27 [tests/024-ispixelsimilar.phpt]
     ========DIFF========
     001+ isSimilar failed. Color [rgba(0, 0, 0, 1)] compared to color [rgba(7, 7, 0, 1)] distance 0.02037706832434 doesn't meet expected result [].
     002+ isPixelSimilar failed. Color [rgba(0, 0, 0, 1)] compared to color [rgba(7, 7, 0, 1)] distance 0.02037706832434 doesn't meet expected result [].
     003+ isSimilar failed. Color [black] compared to color [rgba(10, 0, 0, 1.0)] distance 0.022641187027044 doesn't meet expected result [1].
     004+ isPixelSimilar failed. Color [black] compared to color [rgba(10, 0, 0, 1.0)] distance 0.022641187027044 doesn't meet expected result [1].
     ========DONE========

I don't see any relevant change in IM changelog :(

ImageMagick version => ImageMagick 6.9.1-4 Q16 x86_64 2015-06-02 http://www.imagemagick.org

**Comment by Danack** [comment]
Thanks, it looks like the ImageMagick function IsPixelWandSimilar is broken. To the upstream-mobile!

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=27748&p=122613

I have no what has changed as not only is there nothing in the changelog, but also ImageMagick's SVN repo appears unavailable.

**Comment by Danack** [comment]
They say it will be fixed in ImageMagick 6.9.1-5 Beta.

Do you have any advice on what action Imagick could/should do to allow people to know that ImageMagick 6.9.1-4 is a buggy version?

**Comment by Danack** [comment]
I'm going to close this as it appears to be fixed in the current version of ImageMagick. 

btw they have a mirror on git now - https://github.com/ImageMagick/ImageMagick
